/*
 jQuery JavaScript Library v2.2.0
 http://jquery.com/

 Includes Sizzle.js
 http://sizzlejs.com/

 Copyright jQuery Foundation and other contributors
 Released under the MIT license
 http://jquery.org/license

 Date: 2016-01-08T20:02Z
 Sizzle CSS Selector Engine v2.2.1
 http://sizzlejs.com/

 Copyright jQuery Foundation and other contributors
 Released under the MIT license
 http://jquery.org/license

 Date: 2015-10-17
*/
(function(r,Y){"object"===typeof module&&"object"===typeof module.exports?module.exports=r.document?Y(r,!0):function(r){if(!r.document)throw Error("jQuery requires a window with a document");return Y(r)}:Y(r)})("undefined"!==typeof window?window:this,function(r,Y){function Ia(a){var b=!!a&&"length"in a&&a.length,c=d.type(a);return"function"===c||d.isWindow(a)?!1:"array"===c||0===b||"number"===typeof b&&0<b&&b-1 in a}function Ja(a,b,c){if(d.isFunction(b))return d.grep(a,function(a,d){return!!b.call(a,
d,a)!==c});if(b.nodeType)return d.grep(a,function(a){return a===b!==c});if("string"===typeof b){if(Pb.test(b))return d.filter(b,a,c);b=d.filter(b,a)}return d.grep(a,function(a){return-1<ia.call(b,a)!==c})}function $a(a,b){for(;(a=a[b])&&1!==a.nodeType;);return a}function Qb(a){var b={};d.each(a.match(L)||[],function(a,d){b[d]=!0});return b}function ba(){p.removeEventListener("DOMContentLoaded",ba);r.removeEventListener("load",ba);d.ready()}function pa(){this.expando=d.expando+pa.uid++}function ab(a,
b,c){if(void 0===c&&1===a.nodeType)if(c="data-"+b.replace(bb,"-$&").toLowerCase(),c=a.getAttribute(c),"string"===typeof c){try{c="true"===c?!0:"false"===c?!1:"null"===c?null:+c+""===c?+c:Rb.test(c)?d.parseJSON(c):c}catch(e){}w.set(a,b,c)}else c=void 0;return c}function cb(a,b,c,e){var f=1,g=20,h=e?function(){return e.cur()}:function(){return d.css(a,b,"")},l=h(),k=c&&c[3]||(d.cssNumber[b]?"":"px"),m=(d.cssNumber[b]||"px"!==k&&+l)&&qa.exec(d.css(a,b));if(m&&m[3]!==k){k=k||m[3];c=c||[];m=+l||1;do f=
f||".5",m/=f,d.style(a,b,m+k);while(f!==(f=h()/l)&&1!==f&&--g)}if(c){m=+m||+l||0;var q=c[1]?m+(c[1]+1)*c[2]:+c[2];e&&(e.unit=k,e.start=m,e.end=q)}return q}function G(a,b){var c="undefined"!==typeof a.getElementsByTagName?a.getElementsByTagName(b||"*"):"undefined"!==typeof a.querySelectorAll?a.querySelectorAll(b||"*"):[];return void 0===b||b&&d.nodeName(a,b)?d.merge([a],c):c}function Ka(a,b){for(var c=0,d=a.length;c<d;c++)t.set(a[c],"globalEval",!b||t.get(b[c],"globalEval"))}function db(a,b,c,e,f){for(var g,
h,l,k=b.createDocumentFragment(),m=[],q=0,u=a.length;q<u;q++)if((g=a[q])||0===g)if("object"===d.type(g))d.merge(m,g.nodeType?[g]:g);else if(Sb.test(g)){h=h||k.appendChild(b.createElement("div"));l=(eb.exec(g)||["",""])[1].toLowerCase();l=F[l]||F._default;h.innerHTML=l[1]+d.htmlPrefilter(g)+l[2];for(l=l[0];l--;)h=h.lastChild;d.merge(m,h.childNodes);h=k.firstChild;h.textContent=""}else m.push(b.createTextNode(g));k.textContent="";for(q=0;g=m[q++];)if(e&&-1<d.inArray(g,e))f&&f.push(g);else if(a=d.contains(g.ownerDocument,
g),h=G(k.appendChild(g),"script"),a&&Ka(h),c)for(l=0;g=h[l++];)fb.test(g.type||"")&&c.push(g);return k}function ra(){return!0}function ja(){return!1}function gb(){try{return p.activeElement}catch(a){}}function La(a,b,c,e,f,g){var h;if("object"===typeof b){"string"!==typeof c&&(e=e||c,c=void 0);for(h in b)La(a,h,c,e,b[h],g);return a}null==e&&null==f?(f=c,e=c=void 0):null==f&&("string"===typeof c?(f=e,e=void 0):(f=e,e=c,c=void 0));if(!1===f)f=ja;else if(!f)return this;if(1===g){var l=f;f=function(a){d().off(a);
return l.apply(this,arguments)};f.guid=l.guid||(l.guid=d.guid++)}return a.each(function(){d.event.add(this,b,f,e,c)})}function hb(a,b){return d.nodeName(a,"table")&&d.nodeName(11!==b.nodeType?b:b.firstChild,"tr")?a.getElementsByTagName("tbody")[0]||a:a}function Tb(a){a.type=(null!==a.getAttribute("type"))+"/"+a.type;return a}function Ub(a){var b=Vb.exec(a.type);b?a.type=b[1]:a.removeAttribute("type");return a}function ib(a,b){var c;if(1===b.nodeType){if(t.hasData(a)){var e=t.access(a);var f=t.set(b,
e);if(e=e.events)for(g in delete f.handle,f.events={},e)for(f=0,c=e[g].length;f<c;f++)d.event.add(b,g,e[g][f])}if(w.hasData(a)){var g=w.access(a);g=d.extend({},g);w.set(b,g)}}}function Z(a,b,c,e){b=jb.apply([],b);var f,g=0,h=a.length,l=h-1,k=b[0],m=d.isFunction(k);if(m||1<h&&"string"===typeof k&&!x.checkClone&&Wb.test(k))return a.each(function(d){var f=a.eq(d);m&&(b[0]=k.call(this,d,f.html()));Z(f,b,c,e)});if(h){var q=db(b,a[0].ownerDocument,!1,a,e);var u=q.firstChild;1===q.childNodes.length&&(q=
u);if(u||e){u=d.map(G(q,"script"),Tb);for(f=u.length;g<h;g++){var n=q;g!==l&&(n=d.clone(n,!0,!0),f&&d.merge(u,G(n,"script")));c.call(a[g],n,g)}if(f)for(q=u[u.length-1].ownerDocument,d.map(u,Ub),g=0;g<f;g++)n=u[g],fb.test(n.type||"")&&!t.access(n,"globalEval")&&d.contains(q,n)&&(n.src?d._evalUrl&&d._evalUrl(n.src):d.globalEval(n.textContent.replace(Xb,"")))}}return a}function kb(a,b,c){for(var e=b?d.filter(b,a):a,f=0;null!=(b=e[f]);f++)c||1!==b.nodeType||d.cleanData(G(b)),b.parentNode&&(c&&d.contains(b.ownerDocument,
b)&&Ka(G(b,"script")),b.parentNode.removeChild(b));return a}function lb(a,b){var c=d(b.createElement(a)).appendTo(b.body),e=d.css(c[0],"display");c.detach();return e}function Ma(a){var b=p,c=mb[a];c||(c=lb(a,b),"none"!==c&&c||(ya=(ya||d("<iframe frameborder='0' width='0' height='0'/>")).appendTo(b.documentElement),b=ya[0].contentDocument,b.write(),b.close(),c=lb(a,b),ya.detach()),mb[a]=c);return c}function ka(a,b,c){var e=a.style;if(c=c||Ba(a)){var f=c.getPropertyValue(b)||c[b];""!==f||d.contains(a.ownerDocument,
a)||(f=d.style(a,b));if(!x.pixelMarginRight()&&Na.test(f)&&nb.test(b)){a=e.width;b=e.minWidth;var g=e.maxWidth;e.minWidth=e.maxWidth=e.width=f;f=c.width;e.width=a;e.minWidth=b;e.maxWidth=g}}return void 0!==f?f+"":f}function Oa(a,b){return{get:function(){if(a())delete this.get;else return(this.get=b).apply(this,arguments)}}}function ob(a){if(a in pb)return a;for(var b=a[0].toUpperCase()+a.slice(1),c=qb.length;c--;)if(a=qb[c]+b,a in pb)return a}function rb(a,b,c){return(a=qa.exec(b))?Math.max(0,a[2]-
(c||0))+(a[3]||"px"):b}function sb(a,b,c,e,f){b=c===(e?"border":"content")?4:"width"===b?1:0;for(var g=0;4>b;b+=2)"margin"===c&&(g+=d.css(a,c+K[b],!0,f)),e?("content"===c&&(g-=d.css(a,"padding"+K[b],!0,f)),"margin"!==c&&(g-=d.css(a,"border"+K[b]+"Width",!0,f))):(g+=d.css(a,"padding"+K[b],!0,f),"padding"!==c&&(g+=d.css(a,"border"+K[b]+"Width",!0,f)));return g}function tb(a,b,c){var e=!0,f="width"===b?a.offsetWidth:a.offsetHeight,g=Ba(a),h="border-box"===d.css(a,"boxSizing",!1,g);p.msFullscreenElement&&
r.top!==r&&a.getClientRects().length&&(f=Math.round(100*a.getBoundingClientRect()[b]));if(0>=f||null==f){f=ka(a,b,g);if(0>f||null==f)f=a.style[b];if(Na.test(f))return f;e=h&&(x.boxSizingReliable()||f===a.style[b]);f=parseFloat(f)||0}return f+sb(a,b,c||(h?"border":"content"),e,g)+"px"}function ub(a,b){for(var c,e,f,g=[],h=0,l=a.length;h<l;h++)e=a[h],e.style&&(g[h]=t.get(e,"olddisplay"),c=e.style.display,b?(g[h]||"none"!==c||(e.style.display=""),""===e.style.display&&U(e)&&(g[h]=t.access(e,"olddisplay",
Ma(e.nodeName)))):(f=U(e),"none"===c&&f||t.set(e,"olddisplay",f?c:d.css(e,"display"))));for(h=0;h<l;h++)e=a[h],!e.style||b&&"none"!==e.style.display&&""!==e.style.display||(e.style.display=b?g[h]||"":"none");return a}function E(a,b,c,d,f){return new E.prototype.init(a,b,c,d,f)}function vb(){r.setTimeout(function(){la=void 0});return la=d.now()}function Ca(a,b){var c=0,d={height:a};for(b=b?1:0;4>c;c+=2-b){var f=K[c];d["margin"+f]=d["padding"+f]=a}b&&(d.opacity=d.width=a);return d}function wb(a,b,c){for(var d,
f=(O.tweeners[b]||[]).concat(O.tweeners["*"]),g=0,h=f.length;g<h;g++)if(d=f[g].call(c,b,a))return d}function Yb(a,b){var c,e;for(c in a){var f=d.camelCase(c);var g=b[f];var h=a[c];d.isArray(h)&&(g=h[1],h=a[c]=h[0]);c!==f&&(a[f]=h,delete a[c]);if((e=d.cssHooks[f])&&"expand"in e)for(c in h=e.expand(h),delete a[f],h)c in a||(a[c]=h[c],b[c]=g);else b[f]=g}}function O(a,b,c){var e,f=0,g=O.prefilters.length,h=d.Deferred().always(function(){delete l.elem}),l=function(){if(e)return!1;var b=la||vb();b=Math.max(0,
k.startTime+k.duration-b);for(var c=1-(b/k.duration||0),d=0,f=k.tweens.length;d<f;d++)k.tweens[d].run(c);h.notifyWith(a,[k,c,b]);if(1>c&&f)return b;h.resolveWith(a,[k]);return!1},k=h.promise({elem:a,props:d.extend({},b),opts:d.extend(!0,{specialEasing:{},easing:d.easing._default},c),originalProperties:b,originalOptions:c,startTime:la||vb(),duration:c.duration,tweens:[],createTween:function(b,c){var e=d.Tween(a,k.opts,b,c,k.opts.specialEasing[b]||k.opts.easing);k.tweens.push(e);return e},stop:function(b){var c=
0,d=b?k.tweens.length:0;if(e)return this;for(e=!0;c<d;c++)k.tweens[c].run(1);b?(h.notifyWith(a,[k,1,0]),h.resolveWith(a,[k,b])):h.rejectWith(a,[k,b]);return this}});c=k.props;for(Yb(c,k.opts.specialEasing);f<g;f++)if(b=O.prefilters[f].call(k,a,c,k.opts))return d.isFunction(b.stop)&&(d._queueHooks(k.elem,k.opts.queue).stop=d.proxy(b.stop,b)),b;d.map(c,wb,k);d.isFunction(k.opts.start)&&k.opts.start.call(a,k);d.fx.timer(d.extend(l,{elem:a,anim:k,queue:k.opts.queue}));return k.progress(k.opts.progress).done(k.opts.done,
k.opts.complete).fail(k.opts.fail).always(k.opts.always)}function ca(a){return a.getAttribute&&a.getAttribute("class")||""}function xb(a){return function(b,c){"string"!==typeof b&&(c=b,b="*");var e,f=0,g=b.toLowerCase().match(L)||[];if(d.isFunction(c))for(;e=g[f++];)"+"===e[0]?(e=e.slice(1)||"*",(a[e]=a[e]||[]).unshift(c)):(a[e]=a[e]||[]).push(c)}}function yb(a,b,c,e){function f(l){var k;g[l]=!0;d.each(a[l]||[],function(a,d){var l=d(b,c,e);if("string"===typeof l&&!h&&!g[l])return b.dataTypes.unshift(l),
f(l),!1;if(h)return!(k=l)});return k}var g={},h=a===Pa;return f(b.dataTypes[0])||!g["*"]&&f("*")}function Qa(a,b){var c,e,f=d.ajaxSettings.flatOptions||{};for(c in b)void 0!==b[c]&&((f[c]?a:e||(e={}))[c]=b[c]);e&&d.extend(!0,a,e);return a}function Ra(a,b,c,e){var f;if(d.isArray(b))d.each(b,function(b,d){c||Zb.test(a)?e(a,d):Ra(a+"["+("object"===typeof d&&null!=d?b:"")+"]",d,c,e)});else if(c||"object"!==d.type(b))e(a,b);else for(f in b)Ra(a+"["+f+"]",b[f],c,e)}function zb(a){return d.isWindow(a)?a:
9===a.nodeType&&a.defaultView}var T=[],p=r.document,aa=T.slice,jb=T.concat,Sa=T.push,ia=T.indexOf,Da={},$b=Da.toString,Ta=Da.hasOwnProperty,x={},d=function(a,b){return new d.fn.init(a,b)},ac=/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g,bc=/^-ms-/,cc=/-([\da-z])/gi,dc=function(a,b){return b.toUpperCase()};d.fn=d.prototype={jquery:"2.2.0",constructor:d,selector:"",length:0,toArray:function(){return aa.call(this)},get:function(a){return null!=a?0>a?this[a+this.length]:this[a]:aa.call(this)},pushStack:function(a){a=
d.merge(this.constructor(),a);a.prevObject=this;a.context=this.context;return a},each:function(a){return d.each(this,a)},map:function(a){return this.pushStack(d.map(this,function(b,c){return a.call(b,c,b)}))},slice:function(){return this.pushStack(aa.apply(this,arguments))},first:function(){return this.eq(0)},last:function(){return this.eq(-1)},eq:function(a){var b=this.length;a=+a+(0>a?b:0);return this.pushStack(0<=a&&a<b?[this[a]]:[])},end:function(){return this.prevObject||this.constructor()},
push:Sa,sort:T.sort,splice:T.splice};d.extend=d.fn.extend=function(){var a,b,c,e=arguments[0]||{},f=1,g=arguments.length,h=!1;"boolean"===typeof e&&(h=e,e=arguments[f]||{},f++);"object"===typeof e||d.isFunction(e)||(e={});f===g&&(e=this,f--);for(;f<g;f++)if(null!=(a=arguments[f]))for(b in a){var l=e[b];var k=a[b];e!==k&&(h&&k&&(d.isPlainObject(k)||(c=d.isArray(k)))?(c?(c=!1,l=l&&d.isArray(l)?l:[]):l=l&&d.isPlainObject(l)?l:{},e[b]=d.extend(h,l,k)):void 0!==k&&(e[b]=k))}return e};d.extend({expando:"jQuery"+
("2.2.0"+Math.random()).replace(/\D/g,""),isReady:!0,error:function(a){throw Error(a);},noop:function(){},isFunction:function(a){return"function"===d.type(a)},isArray:Array.isArray,isWindow:function(a){return null!=a&&a===a.window},isNumeric:function(a){var b=a&&a.toString();return!d.isArray(a)&&0<=b-parseFloat(b)+1},isPlainObject:function(a){return"object"!==d.type(a)||a.nodeType||d.isWindow(a)||a.constructor&&!Ta.call(a.constructor.prototype,"isPrototypeOf")?!1:!0},isEmptyObject:function(a){for(var b in a)return!1;
return!0},type:function(a){return null==a?a+"":"object"===typeof a||"function"===typeof a?Da[$b.call(a)]||"object":typeof a},globalEval:function(a){var b=eval;if(a=d.trim(a))1===a.indexOf("use strict")?(b=p.createElement("script"),b.text=a,p.head.appendChild(b).parentNode.removeChild(b)):b(a)},camelCase:function(a){return a.replace(bc,"ms-").replace(cc,dc)},nodeName:function(a,b){return a.nodeName&&a.nodeName.toLowerCase()===b.toLowerCase()},each:function(a,b){var c,d=0;if(Ia(a))for(c=a.length;d<
c&&!1!==b.call(a[d],d,a[d]);d++);else for(d in a)if(!1===b.call(a[d],d,a[d]))break;return a},trim:function(a){return null==a?"":(a+"").replace(ac,"")},makeArray:function(a,b){var c=b||[];null!=a&&(Ia(Object(a))?d.merge(c,"string"===typeof a?[a]:a):Sa.call(c,a));return c},inArray:function(a,b,c){return null==b?-1:ia.call(b,a,c)},merge:function(a,b){for(var c=+b.length,d=0,f=a.length;d<c;d++)a[f++]=b[d];a.length=f;return a},grep:function(a,b,c){for(var d=[],f=0,g=a.length,h=!c;f<g;f++)c=!b(a[f],f),
c!==h&&d.push(a[f]);return d},map:function(a,b,c){var d,f=0,g=[];if(Ia(a))for(d=a.length;f<d;f++){var h=b(a[f],f,c);null!=h&&g.push(h)}else for(f in a)h=b(a[f],f,c),null!=h&&g.push(h);return jb.apply([],g)},guid:1,proxy:function(a,b){if("string"===typeof b){var c=a[b];b=a;a=c}if(d.isFunction(a)){var e=aa.call(arguments,2);c=function(){return a.apply(b||this,e.concat(aa.call(arguments)))};c.guid=a.guid=a.guid||d.guid++;return c}},now:Date.now,support:x});"function"===typeof Symbol&&(d.fn[Symbol.iterator]=
T[Symbol.iterator]);d.each("Boolean Number String Function Array Date RegExp Object Error Symbol".split(" "),function(a,b){Da["[object "+b+"]"]=b.toLowerCase()});var na=function(a){function b(a,b,c,d){var e,f,g,v,h=b&&b.ownerDocument,B=b?b.nodeType:9;c=c||[];if("string"!==typeof a||!a||1!==B&&9!==B&&11!==B)return c;if(!d&&((b?b.ownerDocument||b:V)!==z&&sa(b),b=b||z,W)){if(11!==B&&(v=va.exec(a)))if(e=v[1])if(9===B)if(f=b.getElementById(e)){if(f.id===e)return c.push(f),c}else return c;else{if(h&&(f=
h.getElementById(e))&&Aa(b,f)&&f.id===e)return c.push(f),c}else{if(v[2])return ma.apply(c,b.getElementsByTagName(a)),c;if((e=v[3])&&J.getElementsByClassName&&b.getElementsByClassName)return ma.apply(c,b.getElementsByClassName(e)),c}if(!(!J.qsa||Ea[a+" "]||Q&&Q.test(a))){if(1!==B){h=b;var l=a}else if("object"!==b.nodeName.toLowerCase()){(g=b.getAttribute("id"))?g=g.replace(wa,"\\$&"):b.setAttribute("id",g=A);v=ba(a);e=v.length;for(f=fa.test(g)?"#"+g:"[id='"+g+"']";e--;)v[e]=f+" "+n(v[e]);l=v.join(",");
h=ha.test(a)&&q(b.parentNode)||b}if(l)try{return ma.apply(c,h.querySelectorAll(l)),c}catch(Fc){}finally{g===A&&b.removeAttribute("id")}}}return ya(a.replace(T,"$1"),b,c,d)}function c(){function a(c,d){b.push(c+" ")>D.cacheLength&&delete a[b.shift()];return a[c+" "]=d}var b=[];return a}function d(a){a[A]=!0;return a}function f(a){var b=z.createElement("div");try{return!!a(b)}catch(B){return!1}finally{b.parentNode&&b.parentNode.removeChild(b)}}function g(a,b){for(var c=a.split("|"),d=c.length;d--;)D.attrHandle[c[d]]=
b}function h(a,b){var c=b&&a,d=c&&1===a.nodeType&&1===b.nodeType&&(~b.sourceIndex||-2147483648)-(~a.sourceIndex||-2147483648);if(d)return d;if(c)for(;c=c.nextSibling;)if(c===b)return-1;return a?1:-1}function l(a){return function(b){return"input"===b.nodeName.toLowerCase()&&b.type===a}}function k(a){return function(b){var c=b.nodeName.toLowerCase();return("input"===c||"button"===c)&&b.type===a}}function m(a){return d(function(b){b=+b;return d(function(c,d){for(var e,f=a([],c.length,b),g=f.length;g--;)c[e=
f[g]]&&(c[e]=!(d[e]=c[e]))})})}function q(a){return a&&"undefined"!==typeof a.getElementsByTagName&&a}function u(){}function n(a){for(var b=0,c=a.length,d="";b<c;b++)d+=a[b].value;return d}function t(a,b,c){var d=b.dir,e=c&&"parentNode"===d,f=F++;return b.first?function(b,c,f){for(;b=b[d];)if(1===b.nodeType||e)return a(b,c,f)}:function(b,c,g){var v,h=[H,f];if(g)for(;b=b[d];){if((1===b.nodeType||e)&&a(b,c,g))return!0}else for(;b=b[d];)if(1===b.nodeType||e){var B=b[A]||(b[A]={});B=B[b.uniqueID]||(B[b.uniqueID]=
{});if((v=B[d])&&v[0]===H&&v[1]===f)return h[2]=v[2];B[d]=h;if(h[2]=a(b,c,g))return!0}}}function r(a){return 1<a.length?function(b,c,d){for(var e=a.length;e--;)if(!a[e](b,c,d))return!1;return!0}:a[0]}function p(a,b,c,d,e){for(var f,g=[],h=0,v=a.length,B=null!=b;h<v;h++)if(f=a[h])if(!c||c(f,d,e))g.push(f),B&&b.push(h);return g}function x(a,c,e,f,g,h){f&&!f[A]&&(f=x(f));g&&!g[A]&&(g=x(g,h));return d(function(d,h,v,B){var l,k=[],m=[],C=h.length,P;if(!(P=d)){P=c||"*";for(var I=v.nodeType?[v]:v,za=[],
q=0,u=I.length;q<u;q++)b(P,I[q],za);P=za}P=!a||!d&&c?P:p(P,k,a,v,B);I=e?g||(d?a:C||f)?[]:h:P;e&&e(P,I,v,B);if(f){var n=p(I,m);f(n,[],v,B);for(v=n.length;v--;)if(l=n[v])I[m[v]]=!(P[m[v]]=l)}if(d){if(g||a){if(g){n=[];for(v=I.length;v--;)(l=I[v])&&n.push(P[v]=l);g(null,I=[],n,B)}for(v=I.length;v--;)(l=I[v])&&-1<(n=g?K(d,l):k[v])&&(d[n]=!(h[n]=l))}}else I=p(I===h?I.splice(C,I.length):I),g?g(null,h,I,B):ma.apply(h,I)})}function w(a){var b,c,d=a.length,e=D.relative[a[0].type];var f=e||D.relative[" "];for(var g=
e?1:0,h=t(function(a){return a===b},f,!0),v=t(function(a){return-1<K(b,a)},f,!0),l=[function(a,c,d){a=!e&&(d||c!==E)||((b=c).nodeType?h(a,c,d):v(a,c,d));b=null;return a}];g<d;g++)if(f=D.relative[a[g].type])l=[t(r(l),f)];else{f=D.filter[a[g].type].apply(null,a[g].matches);if(f[A]){for(c=++g;c<d&&!D.relative[a[c].type];c++);return x(1<g&&r(l),1<g&&n(a.slice(0,g-1).concat({value:" "===a[g-2].type?"*":""})).replace(T,"$1"),f,g<c&&w(a.slice(g,c)),c<d&&w(a=a.slice(c)),c<d&&n(a))}l.push(f)}return r(l)}function G(a,
c){var e=0<c.length,f=0<a.length,g=function(d,g,h,v,l){var B,k,m=0,C="0",P=d&&[],I=[],q=E,n=d||f&&D.find.TAG("*",l),za=H+=null==q?1:Math.random()||.1,u=n.length;for(l&&(E=g===z||g||l);C!==u&&null!=(B=n[C]);C++){if(f&&B){var t=0;g||B.ownerDocument===z||(sa(B),h=!W);for(;k=a[t++];)if(k(B,g||z,h)){v.push(B);break}l&&(H=za)}e&&((B=!k&&B)&&m--,d&&P.push(B))}m+=C;if(e&&C!==m){for(t=0;k=c[t++];)k(P,I,g,h);if(d){if(0<m)for(;C--;)P[C]||I[C]||(I[C]=X.call(v));I=p(I)}ma.apply(v,I);l&&!d&&0<I.length&&1<m+c.length&&
b.uniqueSort(v)}l&&(H=za,E=q);return P};return e?d(g):g}var y,E,M,N,z,S,W,Q,ta,Fa,Aa,A="sizzle"+1*new Date,V=a.document,H=0,F=0,Ab=c(),L=c(),Ea=c(),R=function(a,b){a===b&&(N=!0);return 0},O={}.hasOwnProperty,ua=[],X=ua.pop,aa=ua.push,ma=ua.push,Z=ua.slice,K=function(a,b){for(var c=0,d=a.length;c<d;c++)if(a[c]===b)return c;return-1},ca=RegExp("[\\x20\\t\\r\\n\\f]+","g"),T=RegExp("^[\\x20\\t\\r\\n\\f]+|((?:^|[^\\\\])(?:\\\\.)*)[\\x20\\t\\r\\n\\f]+$","g"),ja=/^[\x20\t\r\n\f]*,[\x20\t\r\n\f]*/,ka=/^[\x20\t\r\n\f]*([>+~]|[\x20\t\r\n\f])[\x20\t\r\n\f]*/,
la=RegExp("=[\\x20\\t\\r\\n\\f]*([^\\]'\"]*?)[\\x20\\t\\r\\n\\f]*\\]","g"),na=/:((?:\\.|[\w-]|[^\x00-\xa0])+)(?:\((('((?:\\.|[^\\'])*)'|"((?:\\.|[^\\"])*)")|((?:\\.|[^\\()[\]]|\[[\x20\t\r\n\f]*((?:\\.|[\w-]|[^\x00-\xa0])+)(?:[\x20\t\r\n\f]*([*^$|!~]?=)[\x20\t\r\n\f]*(?:'((?:\\.|[^\\'])*)'|"((?:\\.|[^\\"])*)"|((?:\\.|[\w-]|[^\x00-\xa0])+))|)[\x20\t\r\n\f]*\])*)|.*)\)|)/,fa=/^(?:\\.|[\w-]|[^\x00-\xa0])+$/,Y={ID:/^#((?:\\.|[\w-]|[^\x00-\xa0])+)/,CLASS:/^\.((?:\\.|[\w-]|[^\x00-\xa0])+)/,TAG:/^((?:\\.|[\w-]|[^\x00-\xa0])+|[*])/,
ATTR:/^\[[\x20\t\r\n\f]*((?:\\.|[\w-]|[^\x00-\xa0])+)(?:[\x20\t\r\n\f]*([*^$|!~]?=)[\x20\t\r\n\f]*(?:'((?:\\.|[^\\'])*)'|"((?:\\.|[^\\"])*)"|((?:\\.|[\w-]|[^\x00-\xa0])+))|)[\x20\t\r\n\f]*\]/,PSEUDO:/^:((?:\\.|[\w-]|[^\x00-\xa0])+)(?:\((('((?:\\.|[^\\'])*)'|"((?:\\.|[^\\"])*)")|((?:\\.|[^\\()[\]]|\[[\x20\t\r\n\f]*((?:\\.|[\w-]|[^\x00-\xa0])+)(?:[\x20\t\r\n\f]*([*^$|!~]?=)[\x20\t\r\n\f]*(?:'((?:\\.|[^\\'])*)'|"((?:\\.|[^\\"])*)"|((?:\\.|[\w-]|[^\x00-\xa0])+))|)[\x20\t\r\n\f]*\])*)|.*)\)|)/,CHILD:/^:(only|first|last|nth|nth-last)-(child|of-type)(?:\([\x20\t\r\n\f]*(even|odd|(([+-]|)(\d*)n|)[\x20\t\r\n\f]*(?:([+-]|)[\x20\t\r\n\f]*(\d+)|))[\x20\t\r\n\f]*\)|)/i,
bool:/^(?:checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)$/i,needsContext:/^[\x20\t\r\n\f]*[>+~]|:(even|odd|eq|gt|lt|nth|first|last)(?:\([\x20\t\r\n\f]*((?:-\d)?\d*)[\x20\t\r\n\f]*\)|)(?=[^-]|$)/i},pa=/^(?:input|select|textarea|button)$/i,qa=/^h\d$/i,U=/^[^{]+\{\s*\[native \w/,va=/^(?:#([\w-]+)|(\w+)|\.([\w-]+))$/,ha=/[+~]/,wa=/'|\\/g,da=RegExp("\\\\([\\da-f]{1,6}[\\x20\\t\\r\\n\\f]?|([\\x20\\t\\r\\n\\f])|.)","ig"),ea=function(a,
b,c){a="0x"+b-65536;return a!==a||c?b:0>a?String.fromCharCode(a+65536):String.fromCharCode(a>>10|55296,a&1023|56320)},oa=function(){sa()};try{ma.apply(ua=Z.call(V.childNodes),V.childNodes),ua[V.childNodes.length].nodeType}catch(v){ma={apply:ua.length?function(a,b){aa.apply(a,Z.call(b))}:function(a,b){for(var c=a.length,d=0;a[c++]=b[d++];);a.length=c-1}}}var J=b.support={};var xa=b.isXML=function(a){return(a=a&&(a.ownerDocument||a).documentElement)?"HTML"!==a.nodeName:!1};var sa=b.setDocument=function(a){var b;
a=a?a.ownerDocument||a:V;if(a===z||9!==a.nodeType||!a.documentElement)return z;z=a;S=z.documentElement;W=!xa(z);(b=z.defaultView)&&b.top!==b&&(b.addEventListener?b.addEventListener("unload",oa,!1):b.attachEvent&&b.attachEvent("onunload",oa));J.attributes=f(function(a){a.className="i";return!a.getAttribute("className")});J.getElementsByTagName=f(function(a){a.appendChild(z.createComment(""));return!a.getElementsByTagName("*").length});J.getElementsByClassName=U.test(z.getElementsByClassName);J.getById=
f(function(a){S.appendChild(a).id=A;return!z.getElementsByName||!z.getElementsByName(A).length});J.getById?(D.find.ID=function(a,b){if("undefined"!==typeof b.getElementById&&W){var c=b.getElementById(a);return c?[c]:[]}},D.filter.ID=function(a){var b=a.replace(da,ea);return function(a){return a.getAttribute("id")===b}}):(delete D.find.ID,D.filter.ID=function(a){var b=a.replace(da,ea);return function(a){return(a="undefined"!==typeof a.getAttributeNode&&a.getAttributeNode("id"))&&a.value===b}});D.find.TAG=
J.getElementsByTagName?function(a,b){if("undefined"!==typeof b.getElementsByTagName)return b.getElementsByTagName(a);if(J.qsa)return b.querySelectorAll(a)}:function(a,b){var c,d=[],e=0,f=b.getElementsByTagName(a);if("*"===a){for(;c=f[e++];)1===c.nodeType&&d.push(c);return d}return f};D.find.CLASS=J.getElementsByClassName&&function(a,b){if("undefined"!==typeof b.getElementsByClassName&&W)return b.getElementsByClassName(a)};ta=[];Q=[];if(J.qsa=U.test(z.querySelectorAll))f(function(a){S.appendChild(a).innerHTML=
"<a id='"+A+"'></a><select id='"+A+"-\r\\' msallowcapture=''><option selected=''></option></select>";a.querySelectorAll("[msallowcapture^='']").length&&Q.push("[*^$]=[\\x20\\t\\r\\n\\f]*(?:''|\"\")");a.querySelectorAll("[selected]").length||Q.push("\\[[\\x20\\t\\r\\n\\f]*(?:value|checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)");a.querySelectorAll("[id~="+A+"-]").length||Q.push("~=");a.querySelectorAll(":checked").length||
Q.push(":checked");a.querySelectorAll("a#"+A+"+*").length||Q.push(".#.+[+~]")}),f(function(a){var b=z.createElement("input");b.setAttribute("type","hidden");a.appendChild(b).setAttribute("name","D");a.querySelectorAll("[name=d]").length&&Q.push("name[\\x20\\t\\r\\n\\f]*[*^$|!~]?=");a.querySelectorAll(":enabled").length||Q.push(":enabled",":disabled");a.querySelectorAll("*,:x");Q.push(",.*:")});(J.matchesSelector=U.test(Fa=S.matches||S.webkitMatchesSelector||S.mozMatchesSelector||S.oMatchesSelector||
S.msMatchesSelector))&&f(function(a){J.disconnectedMatch=Fa.call(a,"div");Fa.call(a,"[s!='']:x");ta.push("!=",":((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:\\((('((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\")|((?:\\\\.|[^\\\\()[\\]]|\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:[\\x20\\t\\r\\n\\f]*([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:'((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\"|((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+))|)[\\x20\\t\\r\\n\\f]*\\])*)|.*)\\)|)")});Q=Q.length&&new RegExp(Q.join("|"));
ta=ta.length&&new RegExp(ta.join("|"));Aa=(b=U.test(S.compareDocumentPosition))||U.test(S.contains)?function(a,b){var c=9===a.nodeType?a.documentElement:a,d=b&&b.parentNode;return a===d||!!(d&&1===d.nodeType&&(c.contains?c.contains(d):a.compareDocumentPosition&&a.compareDocumentPosition(d)&16))}:function(a,b){if(b)for(;b=b.parentNode;)if(b===a)return!0;return!1};R=b?function(a,b){if(a===b)return N=!0,0;var c=!a.compareDocumentPosition-!b.compareDocumentPosition;if(c)return c;c=(a.ownerDocument||a)===
(b.ownerDocument||b)?a.compareDocumentPosition(b):1;return c&1||!J.sortDetached&&b.compareDocumentPosition(a)===c?a===z||a.ownerDocument===V&&Aa(V,a)?-1:b===z||b.ownerDocument===V&&Aa(V,b)?1:M?K(M,a)-K(M,b):0:c&4?-1:1}:function(a,b){if(a===b)return N=!0,0;var c=0;var d=a.parentNode;var e=b.parentNode,f=[a],g=[b];if(!d||!e)return a===z?-1:b===z?1:d?-1:e?1:M?K(M,a)-K(M,b):0;if(d===e)return h(a,b);for(d=a;d=d.parentNode;)f.unshift(d);for(d=b;d=d.parentNode;)g.unshift(d);for(;f[c]===g[c];)c++;return c?
h(f[c],g[c]):f[c]===V?-1:g[c]===V?1:0};return z};b.matches=function(a,c){return b(a,null,null,c)};b.matchesSelector=function(a,c){(a.ownerDocument||a)!==z&&sa(a);c=c.replace(la,"='$1']");if(!(!J.matchesSelector||!W||Ea[c+" "]||ta&&ta.test(c)||Q&&Q.test(c)))try{var d=Fa.call(a,c);if(d||J.disconnectedMatch||a.document&&11!==a.document.nodeType)return d}catch(P){}return 0<b(c,z,null,[a]).length};b.contains=function(a,b){(a.ownerDocument||a)!==z&&sa(a);return Aa(a,b)};b.attr=function(a,b){(a.ownerDocument||
a)!==z&&sa(a);var c=D.attrHandle[b.toLowerCase()];c=c&&O.call(D.attrHandle,b.toLowerCase())?c(a,b,!W):void 0;return void 0!==c?c:J.attributes||!W?a.getAttribute(b):(c=a.getAttributeNode(b))&&c.specified?c.value:null};b.error=function(a){throw Error("Syntax error, unrecognized expression: "+a);};b.uniqueSort=function(a){var b,c=[],d=0,e=0;N=!J.detectDuplicates;M=!J.sortStable&&a.slice(0);a.sort(R);if(N){for(;b=a[e++];)b===a[e]&&(d=c.push(e));for(;d--;)a.splice(c[d],1)}M=null;return a};var ia=b.getText=
function(a){var b="",c=0;var d=a.nodeType;if(!d)for(;d=a[c++];)b+=ia(d);else if(1===d||9===d||11===d){if("string"===typeof a.textContent)return a.textContent;for(a=a.firstChild;a;a=a.nextSibling)b+=ia(a)}else if(3===d||4===d)return a.nodeValue;return b};var D=b.selectors={cacheLength:50,createPseudo:d,match:Y,attrHandle:{},find:{},relative:{">":{dir:"parentNode",first:!0}," ":{dir:"parentNode"},"+":{dir:"previousSibling",first:!0},"~":{dir:"previousSibling"}},preFilter:{ATTR:function(a){a[1]=a[1].replace(da,
ea);a[3]=(a[3]||a[4]||a[5]||"").replace(da,ea);"~="===a[2]&&(a[3]=" "+a[3]+" ");return a.slice(0,4)},CHILD:function(a){a[1]=a[1].toLowerCase();"nth"===a[1].slice(0,3)?(a[3]||b.error(a[0]),a[4]=+(a[4]?a[5]+(a[6]||1):2*("even"===a[3]||"odd"===a[3])),a[5]=+(a[7]+a[8]||"odd"===a[3])):a[3]&&b.error(a[0]);return a},PSEUDO:function(a){var b,c=!a[6]&&a[2];if(Y.CHILD.test(a[0]))return null;a[3]?a[2]=a[4]||a[5]||"":c&&na.test(c)&&(b=ba(c,!0))&&(b=c.indexOf(")",c.length-b)-c.length)&&(a[0]=a[0].slice(0,b),a[2]=
c.slice(0,b));return a.slice(0,3)}},filter:{TAG:function(a){var b=a.replace(da,ea).toLowerCase();return"*"===a?function(){return!0}:function(a){return a.nodeName&&a.nodeName.toLowerCase()===b}},CLASS:function(a){var b=Ab[a+" "];return b||(b=new RegExp("(^|[\\x20\\t\\r\\n\\f])"+a+"([\\x20\\t\\r\\n\\f]|$)"),Ab(a,function(a){return b.test("string"===typeof a.className&&a.className||"undefined"!==typeof a.getAttribute&&a.getAttribute("class")||"")}))},ATTR:function(a,c,d){return function(e){e=b.attr(e,
a);if(null==e)return"!="===c;if(!c)return!0;e+="";return"="===c?e===d:"!="===c?e!==d:"^="===c?d&&0===e.indexOf(d):"*="===c?d&&-1<e.indexOf(d):"$="===c?d&&e.slice(-d.length)===d:"~="===c?-1<(" "+e.replace(ca," ")+" ").indexOf(d):"|="===c?e===d||e.slice(0,d.length+1)===d+"-":!1}},CHILD:function(a,b,c,d,e){var f="nth"!==a.slice(0,3),g="last"!==a.slice(-4),h="of-type"===b;return 1===d&&0===e?function(a){return!!a.parentNode}:function(b,c,l){var k,m;c=f!==g?"nextSibling":"previousSibling";var v=b.parentNode,
B=h&&b.nodeName.toLowerCase();l=!l&&!h;var C=!1;if(v){if(f){for(;c;){for(k=b;k=k[c];)if(h?k.nodeName.toLowerCase()===B:1===k.nodeType)return!1;var q=c="only"===a&&!q&&"nextSibling"}return!0}q=[g?v.firstChild:v.lastChild];if(g&&l){k=v;var n=k[A]||(k[A]={});n=n[k.uniqueID]||(n[k.uniqueID]={});C=n[a]||[];C=(m=C[0]===H&&C[1])&&C[2];for(k=m&&v.childNodes[m];k=++m&&k&&k[c]||(C=m=0)||q.pop();)if(1===k.nodeType&&++C&&k===b){n[a]=[H,m,C];break}}else if(l&&(k=b,n=k[A]||(k[A]={}),n=n[k.uniqueID]||(n[k.uniqueID]=
{}),C=n[a]||[],C=m=C[0]===H&&C[1]),!1===C)for(;(k=++m&&k&&k[c]||(C=m=0)||q.pop())&&((h?k.nodeName.toLowerCase()!==B:1!==k.nodeType)||!++C||(l&&(n=k[A]||(k[A]={}),n=n[k.uniqueID]||(n[k.uniqueID]={}),n[a]=[H,C]),k!==b)););C-=e;return C===d||0===C%d&&0<=C/d}}},PSEUDO:function(a,c){var e=D.pseudos[a]||D.setFilters[a.toLowerCase()]||b.error("unsupported pseudo: "+a);if(e[A])return e(c);if(1<e.length){var f=[a,a,"",c];return D.setFilters.hasOwnProperty(a.toLowerCase())?d(function(a,b){for(var d,f=e(a,c),
g=f.length;g--;)d=K(a,f[g]),a[d]=!(b[d]=f[g])}):function(a){return e(a,0,f)}}return e}},pseudos:{not:d(function(a){var b=[],c=[],e=ra(a.replace(T,"$1"));return e[A]?d(function(a,b,c,d){d=e(a,null,d,[]);for(var f=a.length;f--;)if(c=d[f])a[f]=!(b[f]=c)}):function(a,d,f){b[0]=a;e(b,null,f,c);b[0]=null;return!c.pop()}}),has:d(function(a){return function(c){return 0<b(a,c).length}}),contains:d(function(a){a=a.replace(da,ea);return function(b){return-1<(b.textContent||b.innerText||ia(b)).indexOf(a)}}),
lang:d(function(a){fa.test(a||"")||b.error("unsupported lang: "+a);a=a.replace(da,ea).toLowerCase();return function(b){var c;do if(c=W?b.lang:b.getAttribute("xml:lang")||b.getAttribute("lang"))return c=c.toLowerCase(),c===a||0===c.indexOf(a+"-");while((b=b.parentNode)&&1===b.nodeType);return!1}}),target:function(b){var c=a.location&&a.location.hash;return c&&c.slice(1)===b.id},root:function(a){return a===S},focus:function(a){return a===z.activeElement&&(!z.hasFocus||z.hasFocus())&&!!(a.type||a.href||
~a.tabIndex)},enabled:function(a){return!1===a.disabled},disabled:function(a){return!0===a.disabled},checked:function(a){var b=a.nodeName.toLowerCase();return"input"===b&&!!a.checked||"option"===b&&!!a.selected},selected:function(a){a.parentNode&&a.parentNode.selectedIndex;return!0===a.selected},empty:function(a){for(a=a.firstChild;a;a=a.nextSibling)if(6>a.nodeType)return!1;return!0},parent:function(a){return!D.pseudos.empty(a)},header:function(a){return qa.test(a.nodeName)},input:function(a){return pa.test(a.nodeName)},
button:function(a){var b=a.nodeName.toLowerCase();return"input"===b&&"button"===a.type||"button"===b},text:function(a){var b;return"input"===a.nodeName.toLowerCase()&&"text"===a.type&&(null==(b=a.getAttribute("type"))||"text"===b.toLowerCase())},first:m(function(){return[0]}),last:m(function(a,b){return[b-1]}),eq:m(function(a,b,c){return[0>c?c+b:c]}),even:m(function(a,b){for(var c=0;c<b;c+=2)a.push(c);return a}),odd:m(function(a,b){for(var c=1;c<b;c+=2)a.push(c);return a}),lt:m(function(a,b,c){for(b=
0>c?c+b:c;0<=--b;)a.push(b);return a}),gt:m(function(a,b,c){for(c=0>c?c+b:c;++c<b;)a.push(c);return a})}};D.pseudos.nth=D.pseudos.eq;for(y in{radio:!0,checkbox:!0,file:!0,password:!0,image:!0})D.pseudos[y]=l(y);for(y in{submit:!0,reset:!0})D.pseudos[y]=k(y);u.prototype=D.filters=D.pseudos;D.setFilters=new u;var ba=b.tokenize=function(a,c){var d,e,f,g,h;if(g=L[a+" "])return c?0:g.slice(0);g=a;var l=[];for(h=D.preFilter;g;){if(!k||(d=ja.exec(g)))d&&(g=g.slice(d[0].length)||g),l.push(e=[]);var k=!1;
if(d=ka.exec(g))k=d.shift(),e.push({value:k,type:d[0].replace(T," ")}),g=g.slice(k.length);for(f in D.filter)!(d=Y[f].exec(g))||h[f]&&!(d=h[f](d))||(k=d.shift(),e.push({value:k,type:f,matches:d}),g=g.slice(k.length));if(!k)break}return c?g.length:g?b.error(a):L(a,l).slice(0)};var ra=b.compile=function(a,b){var c,d=[],e=[],f=Ea[a+" "];if(!f){b||(b=ba(a));for(c=b.length;c--;)f=w(b[c]),f[A]?d.push(f):e.push(f);f=Ea(a,G(e,d));f.selector=a}return f};var ya=b.select=function(a,b,c,d){var e,f,g,h="function"===
typeof a&&a,l=!d&&ba(a=h.selector||a);c=c||[];if(1===l.length){var k=l[0]=l[0].slice(0);if(2<k.length&&"ID"===(f=k[0]).type&&J.getById&&9===b.nodeType&&W&&D.relative[k[1].type]){b=(D.find.ID(f.matches[0].replace(da,ea),b)||[])[0];if(!b)return c;h&&(b=b.parentNode);a=a.slice(k.shift().value.length)}for(e=Y.needsContext.test(a)?0:k.length;e--;){f=k[e];if(D.relative[g=f.type])break;if(g=D.find[g])if(d=g(f.matches[0].replace(da,ea),ha.test(k[0].type)&&q(b.parentNode)||b)){k.splice(e,1);a=d.length&&n(k);
if(!a)return ma.apply(c,d),c;break}}}(h||ra(a,l))(d,b,!W,c,!b||ha.test(a)&&q(b.parentNode)||b);return c};J.sortStable=A.split("").sort(R).join("")===A;J.detectDuplicates=!!N;sa();J.sortDetached=f(function(a){return a.compareDocumentPosition(z.createElement("div"))&1});f(function(a){a.innerHTML="<a href='#'></a>";return"#"===a.firstChild.getAttribute("href")})||g("type|href|height|width",function(a,b,c){if(!c)return a.getAttribute(b,"type"===b.toLowerCase()?1:2)});J.attributes&&f(function(a){a.innerHTML=
"<input/>";a.firstChild.setAttribute("value","");return""===a.firstChild.getAttribute("value")})||g("value",function(a,b,c){if(!c&&"input"===a.nodeName.toLowerCase())return a.defaultValue});f(function(a){return null==a.getAttribute("disabled")})||g("checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped",function(a,b,c){var d;if(!c)return!0===a[b]?b.toLowerCase():(d=a.getAttributeNode(b))&&d.specified?d.value:null});return b}(r);
d.find=na;d.expr=na.selectors;d.expr[":"]=d.expr.pseudos;d.uniqueSort=d.unique=na.uniqueSort;d.text=na.getText;d.isXMLDoc=na.isXML;d.contains=na.contains;var fa=function(a,b,c){for(var e=[],f=void 0!==c;(a=a[b])&&9!==a.nodeType;)if(1===a.nodeType){if(f&&d(a).is(c))break;e.push(a)}return e},Bb=function(a,b){for(var c=[];a;a=a.nextSibling)1===a.nodeType&&a!==b&&c.push(a);return c},Cb=d.expr.match.needsContext,Db=/^<([\w-]+)\s*\/?>(?:<\/\1>|)$/,Pb=/^.[^:#\[\.,]*$/;d.filter=function(a,b,c){var e=b[0];
c&&(a=":not("+a+")");return 1===b.length&&1===e.nodeType?d.find.matchesSelector(e,a)?[e]:[]:d.find.matches(a,d.grep(b,function(a){return 1===a.nodeType}))};d.fn.extend({find:function(a){var b,c=this.length,e=[],f=this;if("string"!==typeof a)return this.pushStack(d(a).filter(function(){for(b=0;b<c;b++)if(d.contains(f[b],this))return!0}));for(b=0;b<c;b++)d.find(a,f[b],e);e=this.pushStack(1<c?d.unique(e):e);e.selector=this.selector?this.selector+" "+a:a;return e},filter:function(a){return this.pushStack(Ja(this,
a||[],!1))},not:function(a){return this.pushStack(Ja(this,a||[],!0))},is:function(a){return!!Ja(this,"string"===typeof a&&Cb.test(a)?d(a):a||[],!1).length}});var fc=/^(?:\s*(<[\w\W]+>)[^>]*|#([\w-]*))$/;(d.fn.init=function(a,b,c){if(!a)return this;c=c||gc;if("string"===typeof a){var e="<"===a[0]&&">"===a[a.length-1]&&3<=a.length?[null,a,null]:fc.exec(a);if(!e||!e[1]&&b)return!b||b.jquery?(b||c).find(a):this.constructor(b).find(a);if(e[1]){if(b=b instanceof d?b[0]:b,d.merge(this,d.parseHTML(e[1],b&&
b.nodeType?b.ownerDocument||b:p,!0)),Db.test(e[1])&&d.isPlainObject(b))for(e in b)if(d.isFunction(this[e]))this[e](b[e]);else this.attr(e,b[e])}else(b=p.getElementById(e[2]))&&b.parentNode&&(this.length=1,this[0]=b),this.context=p,this.selector=a;return this}if(a.nodeType)return this.context=this[0]=a,this.length=1,this;if(d.isFunction(a))return void 0!==c.ready?c.ready(a):a(d);void 0!==a.selector&&(this.selector=a.selector,this.context=a.context);return d.makeArray(a,this)}).prototype=d.fn;var gc=
d(p);var hc=/^(?:parents|prev(?:Until|All))/,ic={children:!0,contents:!0,next:!0,prev:!0};d.fn.extend({has:function(a){var b=d(a,this),c=b.length;return this.filter(function(){for(var a=0;a<c;a++)if(d.contains(this,b[a]))return!0})},closest:function(a,b){for(var c,e=0,f=this.length,g=[],h=Cb.test(a)||"string"!==typeof a?d(a,b||this.context):0;e<f;e++)for(c=this[e];c&&c!==b;c=c.parentNode)if(11>c.nodeType&&(h?-1<h.index(c):1===c.nodeType&&d.find.matchesSelector(c,a))){g.push(c);break}return this.pushStack(1<
g.length?d.uniqueSort(g):g)},index:function(a){return a?"string"===typeof a?ia.call(d(a),this[0]):ia.call(this,a.jquery?a[0]:a):this[0]&&this[0].parentNode?this.first().prevAll().length:-1},add:function(a,b){return this.pushStack(d.uniqueSort(d.merge(this.get(),d(a,b))))},addBack:function(a){return this.add(null==a?this.prevObject:this.prevObject.filter(a))}});d.each({parent:function(a){return(a=a.parentNode)&&11!==a.nodeType?a:null},parents:function(a){return fa(a,"parentNode")},parentsUntil:function(a,
b,c){return fa(a,"parentNode",c)},next:function(a){return $a(a,"nextSibling")},prev:function(a){return $a(a,"previousSibling")},nextAll:function(a){return fa(a,"nextSibling")},prevAll:function(a){return fa(a,"previousSibling")},nextUntil:function(a,b,c){return fa(a,"nextSibling",c)},prevUntil:function(a,b,c){return fa(a,"previousSibling",c)},siblings:function(a){return Bb((a.parentNode||{}).firstChild,a)},children:function(a){return Bb(a.firstChild)},contents:function(a){return a.contentDocument||
d.merge([],a.childNodes)}},function(a,b){d.fn[a]=function(c,e){var f=d.map(this,b,c);"Until"!==a.slice(-5)&&(e=c);e&&"string"===typeof e&&(f=d.filter(e,f));1<this.length&&(ic[a]||d.uniqueSort(f),hc.test(a)&&f.reverse());return this.pushStack(f)}});var L=/\S+/g;d.Callbacks=function(a){a="string"===typeof a?Qb(a):d.extend({},a);var b,c,e,f,g=[],h=[],l=-1,k=function(){f=a.once;for(e=b=!0;h.length;l=-1)for(c=h.shift();++l<g.length;)!1===g[l].apply(c[0],c[1])&&a.stopOnFalse&&(l=g.length,c=!1);a.memory||
(c=!1);b=!1;f&&(g=c?[]:"")},m={add:function(){g&&(c&&!b&&(l=g.length-1,h.push(c)),function n(b){d.each(b,function(b,c){d.isFunction(c)?a.unique&&m.has(c)||g.push(c):c&&c.length&&"string"!==d.type(c)&&n(c)})}(arguments),c&&!b&&k());return this},remove:function(){d.each(arguments,function(a,b){for(var c;-1<(c=d.inArray(b,g,c));)g.splice(c,1),c<=l&&l--});return this},has:function(a){return a?-1<d.inArray(a,g):0<g.length},empty:function(){g&&(g=[]);return this},disable:function(){f=h=[];g=c="";return this},
disabled:function(){return!g},lock:function(){f=h=[];c||(g=c="");return this},locked:function(){return!!f},fireWith:function(a,c){f||(c=c||[],c=[a,c.slice?c.slice():c],h.push(c),b||k());return this},fire:function(){m.fireWith(this,arguments);return this},fired:function(){return!!e}};return m};d.extend({Deferred:function(a){var b=[["resolve","done",d.Callbacks("once memory"),"resolved"],["reject","fail",d.Callbacks("once memory"),"rejected"],["notify","progress",d.Callbacks("memory")]],c="pending",
e={state:function(){return c},always:function(){f.done(arguments).fail(arguments);return this},then:function(){var a=arguments;return d.Deferred(function(c){d.each(b,function(b,g){var h=d.isFunction(a[b])&&a[b];f[g[1]](function(){var a=h&&h.apply(this,arguments);if(a&&d.isFunction(a.promise))a.promise().progress(c.notify).done(c.resolve).fail(c.reject);else c[g[0]+"With"](this===e?c.promise():this,h?[a]:arguments)})});a=null}).promise()},promise:function(a){return null!=a?d.extend(a,e):e}},f={};e.pipe=
e.then;d.each(b,function(a,d){var g=d[2],h=d[3];e[d[1]]=g.add;h&&g.add(function(){c=h},b[a^1][2].disable,b[2][2].lock);f[d[0]]=function(){f[d[0]+"With"](this===f?e:this,arguments);return this};f[d[0]+"With"]=g.fireWith});e.promise(f);a&&a.call(f,f);return f},when:function(a){var b=0,c=aa.call(arguments),e=c.length,f=1!==e||a&&d.isFunction(a.promise)?e:0,g=1===f?a:d.Deferred(),h=function(a,b,c){return function(d){b[a]=this;c[a]=1<arguments.length?aa.call(arguments):d;c===k?g.notifyWith(b,c):--f||g.resolveWith(b,
c)}},l;if(1<e){var k=Array(e);var m=Array(e);for(l=Array(e);b<e;b++)c[b]&&d.isFunction(c[b].promise)?c[b].promise().progress(h(b,m,k)).done(h(b,l,c)).fail(g.reject):--f}f||g.resolveWith(l,c);return g.promise()}});var Ga;d.fn.ready=function(a){d.ready.promise().done(a);return this};d.extend({isReady:!1,readyWait:1,holdReady:function(a){a?d.readyWait++:d.ready(!0)},ready:function(a){(!0===a?--d.readyWait:d.isReady)||(d.isReady=!0,!0!==a&&0<--d.readyWait||(Ga.resolveWith(p,[d]),d.fn.triggerHandler&&
(d(p).triggerHandler("ready"),d(p).off("ready"))))}});d.ready.promise=function(a){Ga||(Ga=d.Deferred(),"complete"===p.readyState||"loading"!==p.readyState&&!p.documentElement.doScroll?r.setTimeout(d.ready):(p.addEventListener("DOMContentLoaded",ba),r.addEventListener("load",ba)));return Ga.promise(a)};d.ready.promise();var X=function(a,b,c,e,f,g,h){var l=0,k=a.length,m=null==c;if("object"===d.type(c))for(l in f=!0,c)X(a,b,l,c[l],!0,g,h);else if(void 0!==e&&(f=!0,d.isFunction(e)||(h=!0),m&&(h?(b.call(a,
e),b=null):(m=b,b=function(a,b,c){return m.call(d(a),c)})),b))for(;l<k;l++)b(a[l],c,h?e:e.call(a[l],l,b(a[l],c)));return f?a:m?b.call(a):k?b(a[0],c):g},va=function(a){return 1===a.nodeType||9===a.nodeType||!+a.nodeType};pa.uid=1;pa.prototype={register:function(a,b){var c=b||{};a.nodeType?a[this.expando]=c:Object.defineProperty(a,this.expando,{value:c,writable:!0,configurable:!0});return a[this.expando]},cache:function(a){if(!va(a))return{};var b=a[this.expando];b||(b={},va(a)&&(a.nodeType?a[this.expando]=
b:Object.defineProperty(a,this.expando,{value:b,configurable:!0})));return b},set:function(a,b,c){var d;a=this.cache(a);if("string"===typeof b)a[b]=c;else for(d in b)a[d]=b[d];return a},get:function(a,b){return void 0===b?this.cache(a):a[this.expando]&&a[this.expando][b]},access:function(a,b,c){if(void 0===b||b&&"string"===typeof b&&void 0===c)return c=this.get(a,b),void 0!==c?c:this.get(a,d.camelCase(b));this.set(a,b,c);return void 0!==c?c:b},remove:function(a,b){var c=a[this.expando];if(void 0!==
c){if(void 0===b)this.register(a);else{if(d.isArray(b))var e=b.concat(b.map(d.camelCase));else{var f=d.camelCase(b);b in c?e=[b,f]:(e=f,e=e in c?[e]:e.match(L)||[])}for(f=e.length;f--;)delete c[e[f]]}if(void 0===b||d.isEmptyObject(c))a.nodeType?a[this.expando]=void 0:delete a[this.expando]}},hasData:function(a){a=a[this.expando];return void 0!==a&&!d.isEmptyObject(a)}};var t=new pa,w=new pa,Rb=/^(?:\{[\w\W]*\}|\[[\w\W]*\])$/,bb=/[A-Z]/g;d.extend({hasData:function(a){return w.hasData(a)||t.hasData(a)},
data:function(a,b,c){return w.access(a,b,c)},removeData:function(a,b){w.remove(a,b)},_data:function(a,b,c){return t.access(a,b,c)},_removeData:function(a,b){t.remove(a,b)}});d.fn.extend({data:function(a,b){var c,e=this[0],f=e&&e.attributes;if(void 0===a){if(this.length){var g=w.get(e);if(1===e.nodeType&&!t.get(e,"hasDataAttrs")){for(c=f.length;c--;)if(f[c]){var h=f[c].name;0===h.indexOf("data-")&&(h=d.camelCase(h.slice(5)),ab(e,h,g[h]))}t.set(e,"hasDataAttrs",!0)}}return g}return"object"===typeof a?
this.each(function(){w.set(this,a)}):X(this,function(b){if(e&&void 0===b){var c=w.get(e,a)||w.get(e,a.replace(bb,"-$&").toLowerCase());if(void 0!==c)return c;var f=d.camelCase(a);c=w.get(e,f);if(void 0!==c)return c;c=ab(e,f,void 0);if(void 0!==c)return c}else f=d.camelCase(a),this.each(function(){var c=w.get(this,f);w.set(this,f,b);-1<a.indexOf("-")&&void 0!==c&&w.set(this,a,b)})},null,b,1<arguments.length,null,!0)},removeData:function(a){return this.each(function(){w.remove(this,a)})}});d.extend({queue:function(a,
b,c){if(a){b=(b||"fx")+"queue";var e=t.get(a,b);c&&(!e||d.isArray(c)?e=t.access(a,b,d.makeArray(c)):e.push(c));return e||[]}},dequeue:function(a,b){b=b||"fx";var c=d.queue(a,b),e=c.length,f=c.shift(),g=d._queueHooks(a,b),h=function(){d.dequeue(a,b)};"inprogress"===f&&(f=c.shift(),e--);f&&("fx"===b&&c.unshift("inprogress"),delete g.stop,f.call(a,h,g));!e&&g&&g.empty.fire()},_queueHooks:function(a,b){var c=b+"queueHooks";return t.get(a,c)||t.access(a,c,{empty:d.Callbacks("once memory").add(function(){t.remove(a,
[b+"queue",c])})})}});d.fn.extend({queue:function(a,b){var c=2;"string"!==typeof a&&(b=a,a="fx",c--);return arguments.length<c?d.queue(this[0],a):void 0===b?this:this.each(function(){var c=d.queue(this,a,b);d._queueHooks(this,a);"fx"===a&&"inprogress"!==c[0]&&d.dequeue(this,a)})},dequeue:function(a){return this.each(function(){d.dequeue(this,a)})},clearQueue:function(a){return this.queue(a||"fx",[])},promise:function(a,b){var c,e=1,f=d.Deferred(),g=this,h=this.length,l=function(){--e||f.resolveWith(g,
[g])};"string"!==typeof a&&(b=a,a=void 0);for(a=a||"fx";h--;)(c=t.get(g[h],a+"queueHooks"))&&c.empty&&(e++,c.empty.add(l));l();return f.promise(b)}});var Eb=/[+-]?(?:\d*\.|)\d+(?:[eE][+-]?\d+|)/.source,qa=new RegExp("^(?:([+-])=|)("+Eb+")([a-z%]*)$","i"),K=["Top","Right","Bottom","Left"],U=function(a,b){a=b||a;return"none"===d.css(a,"display")||!d.contains(a.ownerDocument,a)},Fb=/^(?:checkbox|radio)$/i,eb=/<([\w:-]+)/,fb=/^$|\/(?:java|ecma)script/i,F={option:[1,"<select multiple='multiple'>","</select>"],
thead:[1,"<table>","</table>"],col:[2,"<table><colgroup>","</colgroup></table>"],tr:[2,"<table><tbody>","</tbody></table>"],td:[3,"<table><tbody><tr>","</tr></tbody></table>"],_default:[0,"",""]};F.optgroup=F.option;F.tbody=F.tfoot=F.colgroup=F.caption=F.thead;F.th=F.td;var Sb=/<|&#?\w+;/;(function(){var a=p.createDocumentFragment().appendChild(p.createElement("div")),b=p.createElement("input");b.setAttribute("type","radio");b.setAttribute("checked","checked");b.setAttribute("name","t");a.appendChild(b);
x.checkClone=a.cloneNode(!0).cloneNode(!0).lastChild.checked;a.innerHTML="<textarea>x</textarea>";x.noCloneChecked=!!a.cloneNode(!0).lastChild.defaultValue})();var jc=/^key/,kc=/^(?:mouse|pointer|contextmenu|drag|drop)|click/,Gb=/^([^.]*)(?:\.(.+)|)/;d.event={global:{},add:function(a,b,c,e,f){var g,h,l,k,m;if(l=t.get(a)){if(c.handler){var q=c;c=q.handler;f=q.selector}c.guid||(c.guid=d.guid++);(h=l.events)||(h=l.events={});(g=l.handle)||(g=l.handle=function(b){return"undefined"!==typeof d&&d.event.triggered!==
b.type?d.event.dispatch.apply(a,arguments):void 0});b=(b||"").match(L)||[""];for(l=b.length;l--;){var u=Gb.exec(b[l])||[];var n=k=u[1];var r=(u[2]||"").split(".").sort();n&&(u=d.event.special[n]||{},n=(f?u.delegateType:u.bindType)||n,u=d.event.special[n]||{},k=d.extend({type:n,origType:k,data:e,handler:c,guid:c.guid,selector:f,needsContext:f&&d.expr.match.needsContext.test(f),namespace:r.join(".")},q),(m=h[n])||(m=h[n]=[],m.delegateCount=0,u.setup&&!1!==u.setup.call(a,e,r,g)||a.addEventListener&&
a.addEventListener(n,g)),u.add&&(u.add.call(a,k),k.handler.guid||(k.handler.guid=c.guid)),f?m.splice(m.delegateCount++,0,k):m.push(k),d.event.global[n]=!0)}}},remove:function(a,b,c,e,f){var g,h,l,k,m,q=t.hasData(a)&&t.get(a);if(q&&(l=q.events)){b=(b||"").match(L)||[""];for(k=b.length;k--;){var u=Gb.exec(b[k])||[];var n=m=u[1];var r=(u[2]||"").split(".").sort();if(n){var p=d.event.special[n]||{};n=(e?p.delegateType:p.bindType)||n;var x=l[n]||[];u=u[2]&&new RegExp("(^|\\.)"+r.join("\\.(?:.*\\.|)")+
"(\\.|$)");for(h=g=x.length;g--;){var w=x[g];!f&&m!==w.origType||c&&c.guid!==w.guid||u&&!u.test(w.namespace)||e&&e!==w.selector&&("**"!==e||!w.selector)||(x.splice(g,1),w.selector&&x.delegateCount--,p.remove&&p.remove.call(a,w))}h&&!x.length&&(p.teardown&&!1!==p.teardown.call(a,r,q.handle)||d.removeEvent(a,n,q.handle),delete l[n])}else for(n in l)d.event.remove(a,n+b[k],c,e,!0)}d.isEmptyObject(l)&&t.remove(a,"handle events")}},dispatch:function(a){a=d.event.fix(a);var b,c,e,f=aa.call(arguments);var g=
(t.get(this,"events")||{})[a.type]||[];var h=d.event.special[a.type]||{};f[0]=a;a.delegateTarget=this;if(!h.preDispatch||!1!==h.preDispatch.call(this,a)){var l=d.event.handlers.call(this,a,g);for(g=0;(e=l[g++])&&!a.isPropagationStopped();)for(a.currentTarget=e.elem,b=0;(c=e.handlers[b++])&&!a.isImmediatePropagationStopped();)if(!a.rnamespace||a.rnamespace.test(c.namespace))a.handleObj=c,a.data=c.data,c=((d.event.special[c.origType]||{}).handle||c.handler).apply(e.elem,f),void 0!==c&&!1===(a.result=
c)&&(a.preventDefault(),a.stopPropagation());h.postDispatch&&h.postDispatch.call(this,a);return a.result}},handlers:function(a,b){var c,e=[],f=b.delegateCount,g=a.target;if(f&&g.nodeType&&("click"!==a.type||isNaN(a.button)||1>a.button))for(;g!==this;g=g.parentNode||this)if(1===g.nodeType&&(!0!==g.disabled||"click"!==a.type)){var h=[];for(c=0;c<f;c++){var l=b[c];var k=l.selector+" ";void 0===h[k]&&(h[k]=l.needsContext?-1<d(k,this).index(g):d.find(k,this,null,[g]).length);h[k]&&h.push(l)}h.length&&
e.push({elem:g,handlers:h})}f<b.length&&e.push({elem:this,handlers:b.slice(f)});return e},props:"altKey bubbles cancelable ctrlKey currentTarget detail eventPhase metaKey relatedTarget shiftKey target timeStamp view which".split(" "),fixHooks:{},keyHooks:{props:["char","charCode","key","keyCode"],filter:function(a,b){null==a.which&&(a.which=null!=b.charCode?b.charCode:b.keyCode);return a}},mouseHooks:{props:"button buttons clientX clientY offsetX offsetY pageX pageY screenX screenY toElement".split(" "),
filter:function(a,b){var c=b.button;if(null==a.pageX&&null!=b.clientX){var d=a.target.ownerDocument||p;var f=d.documentElement;d=d.body;a.pageX=b.clientX+(f&&f.scrollLeft||d&&d.scrollLeft||0)-(f&&f.clientLeft||d&&d.clientLeft||0);a.pageY=b.clientY+(f&&f.scrollTop||d&&d.scrollTop||0)-(f&&f.clientTop||d&&d.clientTop||0)}a.which||void 0===c||(a.which=c&1?1:c&2?3:c&4?2:0);return a}},fix:function(a){if(a[d.expando])return a;var b=a.type;var c=a,e=this.fixHooks[b];e||(this.fixHooks[b]=e=kc.test(b)?this.mouseHooks:
jc.test(b)?this.keyHooks:{});var f=e.props?this.props.concat(e.props):this.props;a=new d.Event(c);for(b=f.length;b--;){var g=f[b];a[g]=c[g]}a.target||(a.target=p);3===a.target.nodeType&&(a.target=a.target.parentNode);return e.filter?e.filter(a,c):a},special:{load:{noBubble:!0},focus:{trigger:function(){if(this!==gb()&&this.focus)return this.focus(),!1},delegateType:"focusin"},blur:{trigger:function(){if(this===gb()&&this.blur)return this.blur(),!1},delegateType:"focusout"},click:{trigger:function(){if("checkbox"===
this.type&&this.click&&d.nodeName(this,"input"))return this.click(),!1},_default:function(a){return d.nodeName(a.target,"a")}},beforeunload:{postDispatch:function(a){void 0!==a.result&&a.originalEvent&&(a.originalEvent.returnValue=a.result)}}}};d.removeEvent=function(a,b,c){a.removeEventListener&&a.removeEventListener(b,c)};d.Event=function(a,b){if(!(this instanceof d.Event))return new d.Event(a,b);a&&a.type?(this.originalEvent=a,this.type=a.type,this.isDefaultPrevented=a.defaultPrevented||void 0===
a.defaultPrevented&&!1===a.returnValue?ra:ja):this.type=a;b&&d.extend(this,b);this.timeStamp=a&&a.timeStamp||d.now();this[d.expando]=!0};d.Event.prototype={constructor:d.Event,isDefaultPrevented:ja,isPropagationStopped:ja,isImmediatePropagationStopped:ja,preventDefault:function(){var a=this.originalEvent;this.isDefaultPrevented=ra;a&&a.preventDefault()},stopPropagation:function(){var a=this.originalEvent;this.isPropagationStopped=ra;a&&a.stopPropagation()},stopImmediatePropagation:function(){var a=
this.originalEvent;this.isImmediatePropagationStopped=ra;a&&a.stopImmediatePropagation();this.stopPropagation()}};d.each({mouseenter:"mouseover",mouseleave:"mouseout",pointerenter:"pointerover",pointerleave:"pointerout"},function(a,b){d.event.special[a]={delegateType:b,bindType:b,handle:function(a){var c=a.relatedTarget,f=a.handleObj;if(!c||c!==this&&!d.contains(this,c)){a.type=f.origType;var g=f.handler.apply(this,arguments);a.type=b}return g}}});d.fn.extend({on:function(a,b,c,d){return La(this,
a,b,c,d)},one:function(a,b,c,d){return La(this,a,b,c,d,1)},off:function(a,b,c){if(a&&a.preventDefault&&a.handleObj){var e=a.handleObj;d(a.delegateTarget).off(e.namespace?e.origType+"."+e.namespace:e.origType,e.selector,e.handler);return this}if("object"===typeof a){for(e in a)this.off(e,b,a[e]);return this}if(!1===b||"function"===typeof b)c=b,b=void 0;!1===c&&(c=ja);return this.each(function(){d.event.remove(this,a,c,b)})}});var lc=/<(?!area|br|col|embed|hr|img|input|link|meta|param)(([\w:-]+)[^>]*)\/>/gi,
mc=/<script|<style|<link/i,Wb=/checked\s*(?:[^=]|=\s*.checked.)/i,Vb=/^true\/(.*)/,Xb=/^\s*<!(?:\[CDATA\[|--)|(?:\]\]|--)>\s*$/g;d.extend({htmlPrefilter:function(a){return a.replace(lc,"<$1></$2>")},clone:function(a,b,c){var e,f=a.cloneNode(!0),g=d.contains(a.ownerDocument,a);if(!(x.noCloneChecked||1!==a.nodeType&&11!==a.nodeType||d.isXMLDoc(a))){var h=G(f);var l=G(a);var k=0;for(e=l.length;k<e;k++){var m=l[k],q=h[k],u=q.nodeName.toLowerCase();if("input"===u&&Fb.test(m.type))q.checked=m.checked;else if("input"===
u||"textarea"===u)q.defaultValue=m.defaultValue}}if(b)if(c)for(l=l||G(a),h=h||G(f),k=0,e=l.length;k<e;k++)ib(l[k],h[k]);else ib(a,f);h=G(f,"script");0<h.length&&Ka(h,!g&&G(a,"script"));return f},cleanData:function(a){for(var b,c,e,f=d.event.special,g=0;void 0!==(c=a[g]);g++)if(va(c)){if(b=c[t.expando]){if(b.events)for(e in b.events)f[e]?d.event.remove(c,e):d.removeEvent(c,e,b.handle);c[t.expando]=void 0}c[w.expando]&&(c[w.expando]=void 0)}}});d.fn.extend({domManip:Z,detach:function(a){return kb(this,
a,!0)},remove:function(a){return kb(this,a)},text:function(a){return X(this,function(a){return void 0===a?d.text(this):this.empty().each(function(){if(1===this.nodeType||11===this.nodeType||9===this.nodeType)this.textContent=a})},null,a,arguments.length)},append:function(){return Z(this,arguments,function(a){1!==this.nodeType&&11!==this.nodeType&&9!==this.nodeType||hb(this,a).appendChild(a)})},prepend:function(){return Z(this,arguments,function(a){if(1===this.nodeType||11===this.nodeType||9===this.nodeType){var b=
hb(this,a);b.insertBefore(a,b.firstChild)}})},before:function(){return Z(this,arguments,function(a){this.parentNode&&this.parentNode.insertBefore(a,this)})},after:function(){return Z(this,arguments,function(a){this.parentNode&&this.parentNode.insertBefore(a,this.nextSibling)})},empty:function(){for(var a,b=0;null!=(a=this[b]);b++)1===a.nodeType&&(d.cleanData(G(a,!1)),a.textContent="");return this},clone:function(a,b){a=null==a?!1:a;b=null==b?a:b;return this.map(function(){return d.clone(this,a,b)})},
html:function(a){return X(this,function(a){var b=this[0]||{},e=0,f=this.length;if(void 0===a&&1===b.nodeType)return b.innerHTML;if("string"===typeof a&&!mc.test(a)&&!F[(eb.exec(a)||["",""])[1].toLowerCase()]){a=d.htmlPrefilter(a);try{for(;e<f;e++)b=this[e]||{},1===b.nodeType&&(d.cleanData(G(b,!1)),b.innerHTML=a);b=0}catch(g){}}b&&this.empty().append(a)},null,a,arguments.length)},replaceWith:function(){var a=[];return Z(this,arguments,function(b){var c=this.parentNode;0>d.inArray(this,a)&&(d.cleanData(G(this)),
c&&c.replaceChild(b,this))},a)}});d.each({appendTo:"append",prependTo:"prepend",insertBefore:"before",insertAfter:"after",replaceAll:"replaceWith"},function(a,b){d.fn[a]=function(a){for(var c=[],f=d(a),g=f.length-1,h=0;h<=g;h++)a=h===g?this:this.clone(!0),d(f[h])[b](a),Sa.apply(c,a.get());return this.pushStack(c)}});var ya,mb={HTML:"block",BODY:"block"},nb=/^margin/,Na=new RegExp("^("+Eb+")(?!px)[a-z%]+$","i"),Ba=function(a){var b=a.ownerDocument.defaultView;b.opener||(b=r);return b.getComputedStyle(a)},
Ua=function(a,b,c,d){var e,g={};for(e in b)g[e]=a.style[e],a.style[e]=b[e];c=c.apply(a,d||[]);for(e in b)a.style[e]=g[e];return c},ha=p.documentElement;(function(){function a(){h.style.cssText="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;position:relative;display:block;margin:auto;border:1px;padding:1px;top:1%;width:50%";h.innerHTML="";ha.appendChild(g);var a=r.getComputedStyle(h);b="1%"!==a.top;f="2px"===a.marginLeft;c="4px"===a.width;h.style.marginRight="50%";
e="4px"===a.marginRight;ha.removeChild(g)}var b,c,e,f,g=p.createElement("div"),h=p.createElement("div");h.style&&(h.style.backgroundClip="content-box",h.cloneNode(!0).style.backgroundClip="",x.clearCloneStyle="content-box"===h.style.backgroundClip,g.style.cssText="border:0;width:8px;height:0;top:0;left:-9999px;padding:0;margin-top:1px;position:absolute",g.appendChild(h),d.extend(x,{pixelPosition:function(){a();return b},boxSizingReliable:function(){null==c&&a();return c},pixelMarginRight:function(){null==
c&&a();return e},reliableMarginLeft:function(){null==c&&a();return f},reliableMarginRight:function(){var a=h.appendChild(p.createElement("div"));a.style.cssText=h.style.cssText="-webkit-box-sizing:content-box;box-sizing:content-box;display:block;margin:0;border:0;padding:0";a.style.marginRight=a.style.width="0";h.style.width="1px";ha.appendChild(g);var b=!parseFloat(r.getComputedStyle(a).marginRight);ha.removeChild(g);h.removeChild(a);return b}}))})();var nc=/^(none|table(?!-c[ea]).+)/,oc={position:"absolute",
visibility:"hidden",display:"block"},Hb={letterSpacing:"0",fontWeight:"400"},qb=["Webkit","O","Moz","ms"],pb=p.createElement("div").style;d.extend({cssHooks:{opacity:{get:function(a,b){if(b){var c=ka(a,"opacity");return""===c?"1":c}}}},cssNumber:{animationIterationCount:!0,columnCount:!0,fillOpacity:!0,flexGrow:!0,flexShrink:!0,fontWeight:!0,lineHeight:!0,opacity:!0,order:!0,orphans:!0,widows:!0,zIndex:!0,zoom:!0},cssProps:{"float":"cssFloat"},style:function(a,b,c,e){if(a&&3!==a.nodeType&&8!==a.nodeType&&
a.style){var f,g=d.camelCase(b),h=a.style;b=d.cssProps[g]||(d.cssProps[g]=ob(g)||g);var l=d.cssHooks[b]||d.cssHooks[g];if(void 0!==c){var k=typeof c;"string"===k&&(f=qa.exec(c))&&f[1]&&(c=cb(a,b,f),k="number");null!=c&&c===c&&("number"===k&&(c+=f&&f[3]||(d.cssNumber[g]?"":"px")),x.clearCloneStyle||""!==c||0!==b.indexOf("background")||(h[b]="inherit"),l&&"set"in l&&void 0===(c=l.set(a,c,e))||(h[b]=c))}else return l&&"get"in l&&void 0!==(f=l.get(a,!1,e))?f:h[b]}},css:function(a,b,c,e){var f;var g=d.camelCase(b);
b=d.cssProps[g]||(d.cssProps[g]=ob(g)||g);(g=d.cssHooks[b]||d.cssHooks[g])&&"get"in g&&(f=g.get(a,!0,c));void 0===f&&(f=ka(a,b,e));"normal"===f&&b in Hb&&(f=Hb[b]);return""===c||c?(a=parseFloat(f),!0===c||isFinite(a)?a||0:f):f}});d.each(["height","width"],function(a,b){d.cssHooks[b]={get:function(a,e,f){if(e)return nc.test(d.css(a,"display"))&&0===a.offsetWidth?Ua(a,oc,function(){return tb(a,b,f)}):tb(a,b,f)},set:function(a,e,f){var c,h=f&&Ba(a);(f=f&&sb(a,b,f,"border-box"===d.css(a,"boxSizing",!1,
h),h))&&(c=qa.exec(e))&&"px"!==(c[3]||"px")&&(a.style[b]=e,e=d.css(a,b));return rb(a,e,f)}}});d.cssHooks.marginLeft=Oa(x.reliableMarginLeft,function(a,b){if(b)return(parseFloat(ka(a,"marginLeft"))||a.getBoundingClientRect().left-Ua(a,{marginLeft:0},function(){return a.getBoundingClientRect().left}))+"px"});d.cssHooks.marginRight=Oa(x.reliableMarginRight,function(a,b){if(b)return Ua(a,{display:"inline-block"},ka,[a,"marginRight"])});d.each({margin:"",padding:"",border:"Width"},function(a,b){d.cssHooks[a+
b]={expand:function(c){var d=0,f={};for(c="string"===typeof c?c.split(" "):[c];4>d;d++)f[a+K[d]+b]=c[d]||c[d-2]||c[0];return f}};nb.test(a)||(d.cssHooks[a+b].set=rb)});d.fn.extend({css:function(a,b){return X(this,function(a,b,f){var c,e={},l=0;if(d.isArray(b)){f=Ba(a);for(c=b.length;l<c;l++)e[b[l]]=d.css(a,b[l],!1,f);return e}return void 0!==f?d.style(a,b,f):d.css(a,b)},a,b,1<arguments.length)},show:function(){return ub(this,!0)},hide:function(){return ub(this)},toggle:function(a){return"boolean"===
typeof a?a?this.show():this.hide():this.each(function(){U(this)?d(this).show():d(this).hide()})}});d.Tween=E;E.prototype={constructor:E,init:function(a,b,c,e,f,g){this.elem=a;this.prop=c;this.easing=f||d.easing._default;this.options=b;this.start=this.now=this.cur();this.end=e;this.unit=g||(d.cssNumber[c]?"":"px")},cur:function(){var a=E.propHooks[this.prop];return a&&a.get?a.get(this):E.propHooks._default.get(this)},run:function(a){var b,c=E.propHooks[this.prop];this.pos=this.options.duration?b=d.easing[this.easing](a,
this.options.duration*a,0,1,this.options.duration):b=a;this.now=(this.end-this.start)*b+this.start;this.options.step&&this.options.step.call(this.elem,this.now,this);c&&c.set?c.set(this):E.propHooks._default.set(this);return this}};E.prototype.init.prototype=E.prototype;E.propHooks={_default:{get:function(a){return 1!==a.elem.nodeType||null!=a.elem[a.prop]&&null==a.elem.style[a.prop]?a.elem[a.prop]:(a=d.css(a.elem,a.prop,""))&&"auto"!==a?a:0},set:function(a){if(d.fx.step[a.prop])d.fx.step[a.prop](a);
else 1!==a.elem.nodeType||null==a.elem.style[d.cssProps[a.prop]]&&!d.cssHooks[a.prop]?a.elem[a.prop]=a.now:d.style(a.elem,a.prop,a.now+a.unit)}}};E.propHooks.scrollTop=E.propHooks.scrollLeft={set:function(a){a.elem.nodeType&&a.elem.parentNode&&(a.elem[a.prop]=a.now)}};d.easing={linear:function(a){return a},swing:function(a){return.5-Math.cos(a*Math.PI)/2},_default:"swing"};d.fx=E.prototype.init;d.fx.step={};var la,Ha,pc=/^(?:toggle|show|hide)$/,qc=/queueHooks$/;d.Animation=d.extend(O,{tweeners:{"*":[function(a,
b){var c=this.createTween(a,b);cb(c.elem,a,qa.exec(b),c);return c}]},tweener:function(a,b){d.isFunction(a)?(b=a,a=["*"]):a=a.match(L);for(var c,e=0,f=a.length;e<f;e++)c=a[e],O.tweeners[c]=O.tweeners[c]||[],O.tweeners[c].unshift(b)},prefilters:[function(a,b,c){var e,f=this,g={},h=a.style,l=a.nodeType&&U(a),k=t.get(a,"fxshow");if(!c.queue){var m=d._queueHooks(a,"fx");if(null==m.unqueued){m.unqueued=0;var q=m.empty.fire;m.empty.fire=function(){m.unqueued||q()}}m.unqueued++;f.always(function(){f.always(function(){m.unqueued--;
d.queue(a,"fx").length||m.empty.fire()})})}if(1===a.nodeType&&("height"in b||"width"in b)){c.overflow=[h.overflow,h.overflowX,h.overflowY];var u=d.css(a,"display");var n="none"===u?t.get(a,"olddisplay")||Ma(a.nodeName):u;"inline"===n&&"none"===d.css(a,"float")&&(h.display="inline-block")}c.overflow&&(h.overflow="hidden",f.always(function(){h.overflow=c.overflow[0];h.overflowX=c.overflow[1];h.overflowY=c.overflow[2]}));for(e in b)if(n=b[e],pc.exec(n)){delete b[e];var r=r||"toggle"===n;if(n===(l?"hide":
"show"))if("show"===n&&k&&void 0!==k[e])l=!0;else continue;g[e]=k&&k[e]||d.style(a,e)}else u=void 0;if(d.isEmptyObject(g))"inline"===("none"===u?Ma(a.nodeName):u)&&(h.display=u);else for(e in k?"hidden"in k&&(l=k.hidden):k=t.access(a,"fxshow",{}),r&&(k.hidden=!l),l?d(a).show():f.done(function(){d(a).hide()}),f.done(function(){var b;t.remove(a,"fxshow");for(b in g)d.style(a,b,g[b])}),g)b=wb(l?k[e]:0,e,f),e in k||(k[e]=b.start,l&&(b.end=b.start,b.start="width"===e||"height"===e?1:0))}],prefilter:function(a,
b){b?O.prefilters.unshift(a):O.prefilters.push(a)}});d.speed=function(a,b,c){var e=a&&"object"===typeof a?d.extend({},a):{complete:c||!c&&b||d.isFunction(a)&&a,duration:a,easing:c&&b||b&&!d.isFunction(b)&&b};e.duration=d.fx.off?0:"number"===typeof e.duration?e.duration:e.duration in d.fx.speeds?d.fx.speeds[e.duration]:d.fx.speeds._default;if(null==e.queue||!0===e.queue)e.queue="fx";e.old=e.complete;e.complete=function(){d.isFunction(e.old)&&e.old.call(this);e.queue&&d.dequeue(this,e.queue)};return e};
d.fn.extend({fadeTo:function(a,b,c,d){return this.filter(U).css("opacity",0).show().end().animate({opacity:b},a,c,d)},animate:function(a,b,c,e){var f=d.isEmptyObject(a),g=d.speed(b,c,e);b=function(){var b=O(this,d.extend({},a),g);(f||t.get(this,"finish"))&&b.stop(!0)};b.finish=b;return f||!1===g.queue?this.each(b):this.queue(g.queue,b)},stop:function(a,b,c){var e=function(a){var b=a.stop;delete a.stop;b(c)};"string"!==typeof a&&(c=b,b=a,a=void 0);b&&!1!==a&&this.queue(a||"fx",[]);return this.each(function(){var b=
!0,g=null!=a&&a+"queueHooks",h=d.timers,l=t.get(this);if(g)l[g]&&l[g].stop&&e(l[g]);else for(g in l)l[g]&&l[g].stop&&qc.test(g)&&e(l[g]);for(g=h.length;g--;)h[g].elem!==this||null!=a&&h[g].queue!==a||(h[g].anim.stop(c),b=!1,h.splice(g,1));!b&&c||d.dequeue(this,a)})},finish:function(a){!1!==a&&(a=a||"fx");return this.each(function(){var b=t.get(this),c=b[a+"queue"];var e=b[a+"queueHooks"];var f=d.timers,g=c?c.length:0;b.finish=!0;d.queue(this,a,[]);e&&e.stop&&e.stop.call(this,!0);for(e=f.length;e--;)f[e].elem===
this&&f[e].queue===a&&(f[e].anim.stop(!0),f.splice(e,1));for(e=0;e<g;e++)c[e]&&c[e].finish&&c[e].finish.call(this);delete b.finish})}});d.each(["toggle","show","hide"],function(a,b){var c=d.fn[b];d.fn[b]=function(a,d,g){return null==a||"boolean"===typeof a?c.apply(this,arguments):this.animate(Ca(b,!0),a,d,g)}});d.each({slideDown:Ca("show"),slideUp:Ca("hide"),slideToggle:Ca("toggle"),fadeIn:{opacity:"show"},fadeOut:{opacity:"hide"},fadeToggle:{opacity:"toggle"}},function(a,b){d.fn[a]=function(a,d,
f){return this.animate(b,a,d,f)}});d.timers=[];d.fx.tick=function(){var a=0,b=d.timers;for(la=d.now();a<b.length;a++){var c=b[a];c()||b[a]!==c||b.splice(a--,1)}b.length||d.fx.stop();la=void 0};d.fx.timer=function(a){d.timers.push(a);a()?d.fx.start():d.timers.pop()};d.fx.interval=13;d.fx.start=function(){Ha||(Ha=r.setInterval(d.fx.tick,d.fx.interval))};d.fx.stop=function(){r.clearInterval(Ha);Ha=null};d.fx.speeds={slow:600,fast:200,_default:400};d.fn.delay=function(a,b){a=d.fx?d.fx.speeds[a]||a:a;
return this.queue(b||"fx",function(b,d){var c=r.setTimeout(b,a);d.stop=function(){r.clearTimeout(c)}})};(function(){var a=p.createElement("input"),b=p.createElement("select"),c=b.appendChild(p.createElement("option"));a.type="checkbox";x.checkOn=""!==a.value;x.optSelected=c.selected;b.disabled=!0;x.optDisabled=!c.disabled;a=p.createElement("input");a.value="t";a.type="radio";x.radioValue="t"===a.value})();var wa=d.expr.attrHandle;d.fn.extend({attr:function(a,b){return X(this,d.attr,a,b,1<arguments.length)},
removeAttr:function(a){return this.each(function(){d.removeAttr(this,a)})}});d.extend({attr:function(a,b,c){var e,f=a.nodeType;if(3!==f&&8!==f&&2!==f){if("undefined"===typeof a.getAttribute)return d.prop(a,b,c);if(1!==f||!d.isXMLDoc(a)){b=b.toLowerCase();var g=d.attrHooks[b]||(d.expr.match.bool.test(b)?rc:void 0)}if(void 0!==c){if(null===c){d.removeAttr(a,b);return}if(g&&"set"in g&&void 0!==(e=g.set(a,c,b)))return e;a.setAttribute(b,c+"");return c}if(g&&"get"in g&&null!==(e=g.get(a,b)))return e;e=
d.find.attr(a,b);return null==e?void 0:e}},attrHooks:{type:{set:function(a,b){if(!x.radioValue&&"radio"===b&&d.nodeName(a,"input")){var c=a.value;a.setAttribute("type",b);c&&(a.value=c);return b}}}},removeAttr:function(a,b){var c,e=0,f=b&&b.match(L);if(f&&1===a.nodeType)for(;c=f[e++];){var g=d.propFix[c]||c;d.expr.match.bool.test(c)&&(a[g]=!1);a.removeAttribute(c)}}});var rc={set:function(a,b,c){!1===b?d.removeAttr(a,c):a.setAttribute(c,c);return c}};d.each(d.expr.match.bool.source.match(/\w+/g),
function(a,b){var c=wa[b]||d.find.attr;wa[b]=function(a,b,d){if(!d){var e=wa[b];wa[b]=f;var f=null!=c(a,b,d)?b.toLowerCase():null;wa[b]=e}return f}});var sc=/^(?:input|select|textarea|button)$/i,tc=/^(?:a|area)$/i;d.fn.extend({prop:function(a,b){return X(this,d.prop,a,b,1<arguments.length)},removeProp:function(a){return this.each(function(){delete this[d.propFix[a]||a]})}});d.extend({prop:function(a,b,c){var e,f=a.nodeType;if(3!==f&&8!==f&&2!==f){if(1!==f||!d.isXMLDoc(a)){b=d.propFix[b]||b;var g=
d.propHooks[b]}return void 0!==c?g&&"set"in g&&void 0!==(e=g.set(a,c,b))?e:a[b]=c:g&&"get"in g&&null!==(e=g.get(a,b))?e:a[b]}},propHooks:{tabIndex:{get:function(a){var b=d.find.attr(a,"tabindex");return b?parseInt(b,10):sc.test(a.nodeName)||tc.test(a.nodeName)&&a.href?0:-1}}},propFix:{"for":"htmlFor","class":"className"}});x.optSelected||(d.propHooks.selected={get:function(a){(a=a.parentNode)&&a.parentNode&&a.parentNode.selectedIndex;return null}});d.each("tabIndex readOnly maxLength cellSpacing cellPadding rowSpan colSpan useMap frameBorder contentEditable".split(" "),
function(){d.propFix[this.toLowerCase()]=this});var Va=/[\t\r\n\f]/g;d.fn.extend({addClass:function(a){var b,c,e,f,g,h=0;if(d.isFunction(a))return this.each(function(b){d(this).addClass(a.call(this,b,ca(this)))});if("string"===typeof a&&a)for(b=a.match(L)||[];c=this[h++];){var l=ca(c);if(e=1===c.nodeType&&(" "+l+" ").replace(Va," ")){for(g=0;f=b[g++];)0>e.indexOf(" "+f+" ")&&(e+=f+" ");e=d.trim(e);l!==e&&c.setAttribute("class",e)}}return this},removeClass:function(a){var b,c,e,f,g,h=0;if(d.isFunction(a))return this.each(function(b){d(this).removeClass(a.call(this,
b,ca(this)))});if(!arguments.length)return this.attr("class","");if("string"===typeof a&&a)for(b=a.match(L)||[];c=this[h++];){var l=ca(c);if(e=1===c.nodeType&&(" "+l+" ").replace(Va," ")){for(g=0;f=b[g++];)for(;-1<e.indexOf(" "+f+" ");)e=e.replace(" "+f+" "," ");e=d.trim(e);l!==e&&c.setAttribute("class",e)}}return this},toggleClass:function(a,b){var c=typeof a;return"boolean"===typeof b&&"string"===c?b?this.addClass(a):this.removeClass(a):d.isFunction(a)?this.each(function(c){d(this).toggleClass(a.call(this,
c,ca(this),b),b)}):this.each(function(){var b,f;if("string"===c){var g=0;var h=d(this);for(f=a.match(L)||[];b=f[g++];)h.hasClass(b)?h.removeClass(b):h.addClass(b)}else if(void 0===a||"boolean"===c)(b=ca(this))&&t.set(this,"__className__",b),this.setAttribute&&this.setAttribute("class",b||!1===a?"":t.get(this,"__className__")||"")})},hasClass:function(a){var b,c=0;for(a=" "+a+" ";b=this[c++];)if(1===b.nodeType&&-1<(" "+ca(b)+" ").replace(Va," ").indexOf(a))return!0;return!1}});var uc=/\r/g;d.fn.extend({val:function(a){var b,
c,e=this[0];if(arguments.length){var f=d.isFunction(a);return this.each(function(c){1===this.nodeType&&(c=f?a.call(this,c,d(this).val()):a,null==c?c="":"number"===typeof c?c+="":d.isArray(c)&&(c=d.map(c,function(a){return null==a?"":a+""})),b=d.valHooks[this.type]||d.valHooks[this.nodeName.toLowerCase()],b&&"set"in b&&void 0!==b.set(this,c,"value")||(this.value=c))})}if(e){if((b=d.valHooks[e.type]||d.valHooks[e.nodeName.toLowerCase()])&&"get"in b&&void 0!==(c=b.get(e,"value")))return c;c=e.value;
return"string"===typeof c?c.replace(uc,""):null==c?"":c}}});d.extend({valHooks:{option:{get:function(a){return d.trim(a.value)}},select:{get:function(a){for(var b,c=a.options,e=a.selectedIndex,f=(a="select-one"===a.type||0>e)?null:[],g=a?e+1:c.length,h=0>e?g:a?e:0;h<g;h++)if(b=c[h],!(!b.selected&&h!==e||(x.optDisabled?b.disabled:null!==b.getAttribute("disabled"))||b.parentNode.disabled&&d.nodeName(b.parentNode,"optgroup"))){b=d(b).val();if(a)return b;f.push(b)}return f},set:function(a,b){for(var c,
e,f=a.options,g=d.makeArray(b),h=f.length;h--;)if(e=f[h],e.selected=-1<d.inArray(d.valHooks.option.get(e),g))c=!0;c||(a.selectedIndex=-1);return g}}}});d.each(["radio","checkbox"],function(){d.valHooks[this]={set:function(a,b){if(d.isArray(b))return a.checked=-1<d.inArray(d(a).val(),b)}};x.checkOn||(d.valHooks[this].get=function(a){return null===a.getAttribute("value")?"on":a.value})});var Ib=/^(?:focusinfocus|focusoutblur)$/;d.extend(d.event,{trigger:function(a,b,c,e){var f,g,h=[c||p],l=Ta.call(a,
"type")?a.type:a;var k=Ta.call(a,"namespace")?a.namespace.split("."):[];var m=f=c=c||p;if(3!==c.nodeType&&8!==c.nodeType&&!Ib.test(l+d.event.triggered)){-1<l.indexOf(".")&&(k=l.split("."),l=k.shift(),k.sort());var q=0>l.indexOf(":")&&"on"+l;a=a[d.expando]?a:new d.Event(l,"object"===typeof a&&a);a.isTrigger=e?2:3;a.namespace=k.join(".");a.rnamespace=a.namespace?new RegExp("(^|\\.)"+k.join("\\.(?:.*\\.|)")+"(\\.|$)"):null;a.result=void 0;a.target||(a.target=c);b=null==b?[a]:d.makeArray(b,[a]);k=d.event.special[l]||
{};if(e||!k.trigger||!1!==k.trigger.apply(c,b)){if(!e&&!k.noBubble&&!d.isWindow(c)){var u=k.delegateType||l;Ib.test(u+l)||(m=m.parentNode);for(;m;m=m.parentNode)h.push(m),f=m;f===(c.ownerDocument||p)&&h.push(f.defaultView||f.parentWindow||r)}for(f=0;(m=h[f++])&&!a.isPropagationStopped();)a.type=1<f?u:k.bindType||l,(g=(t.get(m,"events")||{})[a.type]&&t.get(m,"handle"))&&g.apply(m,b),(g=q&&m[q])&&g.apply&&va(m)&&(a.result=g.apply(m,b),!1===a.result&&a.preventDefault());a.type=l;e||a.isDefaultPrevented()||
k._default&&!1!==k._default.apply(h.pop(),b)||!va(c)||!q||!d.isFunction(c[l])||d.isWindow(c)||((f=c[q])&&(c[q]=null),d.event.triggered=l,c[l](),d.event.triggered=void 0,f&&(c[q]=f));return a.result}}},simulate:function(a,b,c){a=d.extend(new d.Event,c,{type:a,isSimulated:!0});d.event.trigger(a,null,b);a.isDefaultPrevented()&&c.preventDefault()}});d.fn.extend({trigger:function(a,b){return this.each(function(){d.event.trigger(a,b,this)})},triggerHandler:function(a,b){var c=this[0];if(c)return d.event.trigger(a,
b,c,!0)}});d.each("blur focus focusin focusout load resize scroll unload click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave change select submit keydown keypress keyup error contextmenu".split(" "),function(a,b){d.fn[b]=function(a,d){return 0<arguments.length?this.on(b,null,a,d):this.trigger(b)}});d.fn.extend({hover:function(a,b){return this.mouseenter(a).mouseleave(b||a)}});x.focusin="onfocusin"in r;x.focusin||d.each({focus:"focusin",blur:"focusout"},function(a,b){var c=
function(a){d.event.simulate(b,a.target,d.event.fix(a))};d.event.special[b]={setup:function(){var d=this.ownerDocument||this,f=t.access(d,b);f||d.addEventListener(a,c,!0);t.access(d,b,(f||0)+1)},teardown:function(){var d=this.ownerDocument||this,f=t.access(d,b)-1;f?t.access(d,b,f):(d.removeEventListener(a,c,!0),t.remove(d,b))}}});var oa=r.location,Wa=d.now(),Xa=/\?/;d.parseJSON=function(a){return JSON.parse(a+"")};d.parseXML=function(a){if(!a||"string"!==typeof a)return null;try{var b=(new r.DOMParser).parseFromString(a,
"text/xml")}catch(c){b=void 0}b&&!b.getElementsByTagName("parsererror").length||d.error("Invalid XML: "+a);return b};var vc=/#.*$/,Jb=/([?&])_=[^&]*/,wc=/^(.*?):[ \t]*([^\r\n]*)$/mg,xc=/^(?:GET|HEAD)$/,yc=/^\/\//,Kb={},Pa={},Lb="*/".concat("*"),Ya=p.createElement("a");Ya.href=oa.href;d.extend({active:0,lastModified:{},etag:{},ajaxSettings:{url:oa.href,type:"GET",isLocal:/^(?:about|app|app-storage|.+-extension|file|res|widget):$/.test(oa.protocol),global:!0,processData:!0,async:!0,contentType:"application/x-www-form-urlencoded; charset=UTF-8",
accepts:{"*":Lb,text:"text/plain",html:"text/html",xml:"application/xml, text/xml",json:"application/json, text/javascript"},contents:{xml:/\bxml\b/,html:/\bhtml/,json:/\bjson\b/},responseFields:{xml:"responseXML",text:"responseText",json:"responseJSON"},converters:{"* text":String,"text html":!0,"text json":d.parseJSON,"text xml":d.parseXML},flatOptions:{url:!0,context:!0}},ajaxSetup:function(a,b){return b?Qa(Qa(a,d.ajaxSettings),b):Qa(d.ajaxSettings,a)},ajaxPrefilter:xb(Kb),ajaxTransport:xb(Pa),
ajax:function(a,b){function c(a,b,c,g){var k=b;if(2!==G){G=2;h&&r.clearTimeout(h);e=void 0;f=g||"";y.readyState=0<a?4:0;g=200<=a&&300>a||304===a;if(c){var p=m;for(var z=y,w,A,N,H,E=p.contents,F=p.dataTypes;"*"===F[0];)F.shift(),void 0===w&&(w=p.mimeType||z.getResponseHeader("Content-Type"));if(w)for(A in E)if(E[A]&&E[A].test(w)){F.unshift(A);break}if(F[0]in c)N=F[0];else{for(A in c){if(!F[0]||p.converters[A+" "+F[0]]){N=A;break}H||(H=A)}N=N||H}N?(N!==F[0]&&F.unshift(N),p=c[N]):p=void 0}a:{c=m;w=p;
A=y;N=g;var K;z={};E=c.dataTypes.slice();if(E[1])for(R in c.converters)z[R.toLowerCase()]=c.converters[R];for(H=E.shift();H;){c.responseFields[H]&&(A[c.responseFields[H]]=w);!L&&N&&c.dataFilter&&(w=c.dataFilter(w,c.dataType));var L=H;if(H=E.shift())if("*"===H)H=L;else if("*"!==L&&L!==H){var R=z[L+" "+H]||z["* "+H];if(!R)for(K in z)if(p=K.split(" "),p[1]===H&&(R=z[L+" "+p[0]]||z["* "+p[0]])){!0===R?R=z[K]:!0!==z[K]&&(H=p[0],E.unshift(p[1]));break}if(!0!==R)if(R&&c["throws"])w=R(w);else try{w=R(w)}catch(ec){p=
{state:"parsererror",error:R?ec:"No conversion from "+L+" to "+H};break a}}}p={state:"success",data:w}}if(g)if(m.ifModified&&((k=y.getResponseHeader("Last-Modified"))&&(d.lastModified[M]=k),(k=y.getResponseHeader("etag"))&&(d.etag[M]=k)),204===a||"HEAD"===m.type)k="nocontent";else if(304===a)k="notmodified";else{k=p.state;var S=p.data;var O=p.error;g=!O}else if(O=k,a||!k)k="error",0>a&&(a=0);y.status=a;y.statusText=(b||k)+"";g?n.resolveWith(q,[S,k,y]):n.rejectWith(q,[y,k,O]);y.statusCode(x);x=void 0;
l&&u.trigger(g?"ajaxSuccess":"ajaxError",[y,m,g?S:O]);t.fireWith(q,[y,k]);l&&(u.trigger("ajaxComplete",[y,m]),--d.active||d.event.trigger("ajaxStop"))}}"object"===typeof a&&(b=a,a=void 0);b=b||{};var e,f,g,h,l,k,m=d.ajaxSetup({},b),q=m.context||m,u=m.context&&(q.nodeType||q.jquery)?d(q):d.event,n=d.Deferred(),t=d.Callbacks("once memory"),x=m.statusCode||{},w={},E={},G=0,K="canceled",y={readyState:0,getResponseHeader:function(a){var b;if(2===G){if(!g)for(g={};b=wc.exec(f);)g[b[1].toLowerCase()]=b[2];
b=g[a.toLowerCase()]}return null==b?null:b},getAllResponseHeaders:function(){return 2===G?f:null},setRequestHeader:function(a,b){var c=a.toLowerCase();G||(a=E[c]=E[c]||a,w[a]=b);return this},overrideMimeType:function(a){G||(m.mimeType=a);return this},statusCode:function(a){var b;if(a)if(2>G)for(b in a)x[b]=[x[b],a[b]];else y.always(a[y.status]);return this},abort:function(a){a=a||K;e&&e.abort(a);c(0,a);return this}};n.promise(y).complete=t.add;y.success=y.done;y.error=y.fail;m.url=((a||m.url||oa.href)+
"").replace(vc,"").replace(yc,oa.protocol+"//");m.type=b.method||b.type||m.method||m.type;m.dataTypes=d.trim(m.dataType||"*").toLowerCase().match(L)||[""];if(null==m.crossDomain){var F=p.createElement("a");try{F.href=m.url,F.href=F.href,m.crossDomain=Ya.protocol+"//"+Ya.host!==F.protocol+"//"+F.host}catch(N){m.crossDomain=!0}}m.data&&m.processData&&"string"!==typeof m.data&&(m.data=d.param(m.data,m.traditional));yb(Kb,m,b,y);if(2===G)return y;(l=d.event&&m.global)&&0===d.active++&&d.event.trigger("ajaxStart");
m.type=m.type.toUpperCase();m.hasContent=!xc.test(m.type);var M=m.url;m.hasContent||(m.data&&(M=m.url+=(Xa.test(M)?"&":"?")+m.data,delete m.data),!1===m.cache&&(m.url=Jb.test(M)?M.replace(Jb,"$1_="+Wa++):M+(Xa.test(M)?"&":"?")+"_="+Wa++));m.ifModified&&(d.lastModified[M]&&y.setRequestHeader("If-Modified-Since",d.lastModified[M]),d.etag[M]&&y.setRequestHeader("If-None-Match",d.etag[M]));(m.data&&m.hasContent&&!1!==m.contentType||b.contentType)&&y.setRequestHeader("Content-Type",m.contentType);y.setRequestHeader("Accept",
m.dataTypes[0]&&m.accepts[m.dataTypes[0]]?m.accepts[m.dataTypes[0]]+("*"!==m.dataTypes[0]?", "+Lb+"; q=0.01":""):m.accepts["*"]);for(k in m.headers)y.setRequestHeader(k,m.headers[k]);if(m.beforeSend&&(!1===m.beforeSend.call(q,y,m)||2===G))return y.abort();K="abort";for(k in{success:1,error:1,complete:1})y[k](m[k]);if(e=yb(Pa,m,b,y)){y.readyState=1;l&&u.trigger("ajaxSend",[y,m]);if(2===G)return y;m.async&&0<m.timeout&&(h=r.setTimeout(function(){y.abort("timeout")},m.timeout));try{G=1,e.send(w,c)}catch(N){if(2>
G)c(-1,N);else throw N;}}else c(-1,"No Transport");return y},getJSON:function(a,b,c){return d.get(a,b,c,"json")},getScript:function(a,b){return d.get(a,void 0,b,"script")}});d.each(["get","post"],function(a,b){d[b]=function(a,e,f,g){d.isFunction(e)&&(g=g||f,f=e,e=void 0);return d.ajax(d.extend({url:a,type:b,dataType:g,data:e,success:f},d.isPlainObject(a)&&a))}});d._evalUrl=function(a){return d.ajax({url:a,type:"GET",dataType:"script",async:!1,global:!1,"throws":!0})};d.fn.extend({wrapAll:function(a){if(d.isFunction(a))return this.each(function(b){d(this).wrapAll(a.call(this,
b))});if(this[0]){var b=d(a,this[0].ownerDocument).eq(0).clone(!0);this[0].parentNode&&b.insertBefore(this[0]);b.map(function(){for(var a=this;a.firstElementChild;)a=a.firstElementChild;return a}).append(this)}return this},wrapInner:function(a){return d.isFunction(a)?this.each(function(b){d(this).wrapInner(a.call(this,b))}):this.each(function(){var b=d(this),c=b.contents();c.length?c.wrapAll(a):b.append(a)})},wrap:function(a){var b=d.isFunction(a);return this.each(function(c){d(this).wrapAll(b?a.call(this,
c):a)})},unwrap:function(){return this.parent().each(function(){d.nodeName(this,"body")||d(this).replaceWith(this.childNodes)}).end()}});d.expr.filters.hidden=function(a){return!d.expr.filters.visible(a)};d.expr.filters.visible=function(a){return 0<a.offsetWidth||0<a.offsetHeight||0<a.getClientRects().length};var zc=/%20/g,Zb=/\[\]$/,Mb=/\r?\n/g,Ac=/^(?:submit|button|image|reset|file)$/i,Bc=/^(?:input|select|textarea|keygen)/i;d.param=function(a,b){var c,e=[],f=function(a,b){b=d.isFunction(b)?b():
null==b?"":b;e[e.length]=encodeURIComponent(a)+"="+encodeURIComponent(b)};void 0===b&&(b=d.ajaxSettings&&d.ajaxSettings.traditional);if(d.isArray(a)||a.jquery&&!d.isPlainObject(a))d.each(a,function(){f(this.name,this.value)});else for(c in a)Ra(c,a[c],b,f);return e.join("&").replace(zc,"+")};d.fn.extend({serialize:function(){return d.param(this.serializeArray())},serializeArray:function(){return this.map(function(){var a=d.prop(this,"elements");return a?d.makeArray(a):this}).filter(function(){var a=
this.type;return this.name&&!d(this).is(":disabled")&&Bc.test(this.nodeName)&&!Ac.test(a)&&(this.checked||!Fb.test(a))}).map(function(a,b){var c=d(this).val();return null==c?null:d.isArray(c)?d.map(c,function(a){return{name:b.name,value:a.replace(Mb,"\r\n")}}):{name:b.name,value:c.replace(Mb,"\r\n")}}).get()}});d.ajaxSettings.xhr=function(){try{return new r.XMLHttpRequest}catch(a){}};var Cc={0:200,1223:204},xa=d.ajaxSettings.xhr();x.cors=!!xa&&"withCredentials"in xa;x.ajax=xa=!!xa;d.ajaxTransport(function(a){var b,
c;if(x.cors||xa&&!a.crossDomain)return{send:function(d,f){var e,h=a.xhr();h.open(a.type,a.url,a.async,a.username,a.password);if(a.xhrFields)for(e in a.xhrFields)h[e]=a.xhrFields[e];a.mimeType&&h.overrideMimeType&&h.overrideMimeType(a.mimeType);a.crossDomain||d["X-Requested-With"]||(d["X-Requested-With"]="XMLHttpRequest");for(e in d)h.setRequestHeader(e,d[e]);b=function(a){return function(){b&&(b=c=h.onload=h.onerror=h.onabort=h.onreadystatechange=null,"abort"===a?h.abort():"error"===a?"number"!==
typeof h.status?f(0,"error"):f(h.status,h.statusText):f(Cc[h.status]||h.status,h.statusText,"text"!==(h.responseType||"text")||"string"!==typeof h.responseText?{binary:h.response}:{text:h.responseText},h.getAllResponseHeaders()))}};h.onload=b();c=h.onerror=b("error");void 0!==h.onabort?h.onabort=c:h.onreadystatechange=function(){4===h.readyState&&r.setTimeout(function(){b&&c()})};b=b("abort");try{h.send(a.hasContent&&a.data||null)}catch(l){if(b)throw l;}},abort:function(){b&&b()}}});d.ajaxSetup({accepts:{script:"text/javascript, application/javascript, application/ecmascript, application/x-ecmascript"},
contents:{script:/\b(?:java|ecma)script\b/},converters:{"text script":function(a){d.globalEval(a);return a}}});d.ajaxPrefilter("script",function(a){void 0===a.cache&&(a.cache=!1);a.crossDomain&&(a.type="GET")});d.ajaxTransport("script",function(a){if(a.crossDomain){var b,c;return{send:function(e,f){b=d("<script>").prop({charset:a.scriptCharset,src:a.url}).on("load error",c=function(a){b.remove();c=null;a&&f("error"===a.type?404:200,a.type)});p.head.appendChild(b[0])},abort:function(){c&&c()}}}});
var Nb=[],Za=/(=)\?(?=&|$)|\?\?/;d.ajaxSetup({jsonp:"callback",jsonpCallback:function(){var a=Nb.pop()||d.expando+"_"+Wa++;this[a]=!0;return a}});d.ajaxPrefilter("json jsonp",function(a,b,c){var e,f=!1!==a.jsonp&&(Za.test(a.url)?"url":"string"===typeof a.data&&0===(a.contentType||"").indexOf("application/x-www-form-urlencoded")&&Za.test(a.data)&&"data");if(f||"jsonp"===a.dataTypes[0]){var g=a.jsonpCallback=d.isFunction(a.jsonpCallback)?a.jsonpCallback():a.jsonpCallback;f?a[f]=a[f].replace(Za,"$1"+
g):!1!==a.jsonp&&(a.url+=(Xa.test(a.url)?"&":"?")+a.jsonp+"="+g);a.converters["script json"]=function(){e||d.error(g+" was not called");return e[0]};a.dataTypes[0]="json";var h=r[g];r[g]=function(){e=arguments};c.always(function(){void 0===h?d(r).removeProp(g):r[g]=h;a[g]&&(a.jsonpCallback=b.jsonpCallback,Nb.push(g));e&&d.isFunction(h)&&h(e[0]);e=h=void 0});return"script"}});x.createHTMLDocument=function(){var a=p.implementation.createHTMLDocument("").body;a.innerHTML="<form></form><form></form>";
return 2===a.childNodes.length}();d.parseHTML=function(a,b,c){if(!a||"string"!==typeof a)return null;"boolean"===typeof b&&(c=b,b=!1);b=b||(x.createHTMLDocument?p.implementation.createHTMLDocument(""):p);var e=Db.exec(a);c=!c&&[];if(e)return[b.createElement(e[1])];e=db([a],b,c);c&&c.length&&d(c).remove();return d.merge([],e.childNodes)};var Ob=d.fn.load;d.fn.load=function(a,b,c){if("string"!==typeof a&&Ob)return Ob.apply(this,arguments);var e,f,g=this,h=a.indexOf(" ");if(-1<h){var l=d.trim(a.slice(h));
a=a.slice(0,h)}d.isFunction(b)?(c=b,b=void 0):b&&"object"===typeof b&&(e="POST");0<g.length&&d.ajax({url:a,type:e||"GET",dataType:"html",data:b}).done(function(a){f=arguments;g.html(l?d("<div>").append(d.parseHTML(a)).find(l):a)}).always(c&&function(a,b){g.each(function(){c.apply(g,f||[a.responseText,b,a])})});return this};d.each("ajaxStart ajaxStop ajaxComplete ajaxError ajaxSuccess ajaxSend".split(" "),function(a,b){d.fn[b]=function(a){return this.on(b,a)}});d.expr.filters.animated=function(a){return d.grep(d.timers,
function(b){return a===b.elem}).length};d.offset={setOffset:function(a,b,c){var e=d.css(a,"position"),f=d(a),g={};"static"===e&&(a.style.position="relative");var h=f.offset();var l=d.css(a,"top");var k=d.css(a,"left");("absolute"===e||"fixed"===e)&&-1<(l+k).indexOf("auto")?(k=f.position(),l=k.top,k=k.left):(l=parseFloat(l)||0,k=parseFloat(k)||0);d.isFunction(b)&&(b=b.call(a,c,d.extend({},h)));null!=b.top&&(g.top=b.top-h.top+l);null!=b.left&&(g.left=b.left-h.left+k);"using"in b?b.using.call(a,g):f.css(g)}};
d.fn.extend({offset:function(a){if(arguments.length)return void 0===a?this:this.each(function(b){d.offset.setOffset(this,a,b)});var b=this[0];var c={top:0,left:0},e=b&&b.ownerDocument;if(e){var f=e.documentElement;if(!d.contains(f,b))return c;c=b.getBoundingClientRect();b=zb(e);return{top:c.top+b.pageYOffset-f.clientTop,left:c.left+b.pageXOffset-f.clientLeft}}},position:function(){if(this[0]){var a=this[0],b={top:0,left:0};if("fixed"===d.css(a,"position"))var c=a.getBoundingClientRect();else{var e=
this.offsetParent();c=this.offset();d.nodeName(e[0],"html")||(b=e.offset());b.top+=d.css(e[0],"borderTopWidth",!0)-e.scrollTop();b.left+=d.css(e[0],"borderLeftWidth",!0)-e.scrollLeft()}return{top:c.top-b.top-d.css(a,"marginTop",!0),left:c.left-b.left-d.css(a,"marginLeft",!0)}}},offsetParent:function(){return this.map(function(){for(var a=this.offsetParent;a&&"static"===d.css(a,"position");)a=a.offsetParent;return a||ha})}});d.each({scrollLeft:"pageXOffset",scrollTop:"pageYOffset"},function(a,b){var c=
"pageYOffset"===b;d.fn[a]=function(d){return X(this,function(a,d,e){var f=zb(a);if(void 0===e)return f?f[b]:a[d];f?f.scrollTo(c?f.pageXOffset:e,c?e:f.pageYOffset):a[d]=e},a,d,arguments.length)}});d.each(["top","left"],function(a,b){d.cssHooks[b]=Oa(x.pixelPosition,function(a,e){if(e)return e=ka(a,b),Na.test(e)?d(a).position()[b]+"px":e})});d.each({Height:"height",Width:"width"},function(a,b){d.each({padding:"inner"+a,content:b,"":"outer"+a},function(c,e){d.fn[e]=function(e,g){var f=arguments.length&&
(c||"boolean"!==typeof e),l=c||(!0===e||!0===g?"margin":"border");return X(this,function(b,c,e){return d.isWindow(b)?b.document.documentElement["client"+a]:9===b.nodeType?(c=b.documentElement,Math.max(b.body["scroll"+a],c["scroll"+a],b.body["offset"+a],c["offset"+a],c["client"+a])):void 0===e?d.css(b,c,l):d.style(b,c,e,l)},b,f?e:void 0,f,null)}})});d.fn.extend({bind:function(a,b,c){return this.on(a,null,b,c)},unbind:function(a,b){return this.off(a,null,b)},delegate:function(a,b,c,d){return this.on(b,
a,c,d)},undelegate:function(a,b,c){return 1===arguments.length?this.off(a,"**"):this.off(b,a||"**",c)},size:function(){return this.length}});d.fn.andSelf=d.fn.addBack;"function"===typeof define&&define.amd&&define("jquery",[],function(){return d});var Dc=r.jQuery,Ec=r.$;d.noConflict=function(a){r.$===d&&(r.$=Ec);a&&r.jQuery===d&&(r.jQuery=Dc);return d};Y||(r.jQuery=r.$=d);return d});