/*
 Lightbox v2.8.2
 by Lokesh Dhakar

 More info:
 http://lokeshdhakar.com/projects/lightbox2/

 Copyright 2007, 2015 Lokesh Dhakar
 Released under the MIT license
 https://github.com/lokesh/lightbox2/blob/master/LICENSE
*/
(function(b,c){"function"===typeof define&&define.amd?define(["jquery"],c):"object"===typeof exports?module.exports=c(require("jquery")):b.lightbox=c(b.jQuery)})(this,function(b){function c(a){this.album=[];this.currentImageIndex=void 0;this.init();this.options=b.extend({},this.constructor.defaults);this.option(a)}c.defaults={albumLabel:"Imagem %1 de %2",alwaysShowNavOnTouchDevices:!1,fadeDuration:500,fitImagesInViewport:!0,positionFromTop:50,resizeDuration:700,showImageNumberLabel:!0,wrapAround:!1,
disableScrolling:!1};c.prototype.option=function(a){b.extend(this.options,a)};c.prototype.imageCountLabel=function(a,b){return this.options.albumLabel.replace(/%1/g,a).replace(/%2/g,b)};c.prototype.init=function(){this.enable();this.build()};c.prototype.enable=function(){var a=this;b("body").on("click","a[rel^=lightbox], area[rel^=lightbox], a[data-lightbox], area[data-lightbox]",function(d){a.start(b(d.currentTarget));return!1})};c.prototype.build=function(){var a=this;b('<div id="lightboxOverlay" class="lightboxOverlay"></div><div id="lightbox" class="lightbox"><div class="lb-outerContainer"><div class="lb-container"><img class="lb-image" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" /><div class="lb-nav"><a class="lb-prev" href="" ></a><a class="lb-next" href="" ></a></div><div class="lb-loader"><a class="lb-cancel"></a></div></div></div><div class="lb-dataContainer"><div class="lb-data"><div class="lb-details"><span class="lb-caption"></span><span class="lb-number"></span></div><div class="lb-closeContainer"><a class="lb-close"></a></div></div></div></div>').appendTo(b("body"));
this.$lightbox=b("#lightbox");this.$overlay=b("#lightboxOverlay");this.$outerContainer=this.$lightbox.find(".lb-outerContainer");this.$container=this.$lightbox.find(".lb-container");this.containerTopPadding=parseInt(this.$container.css("padding-top"),10);this.containerRightPadding=parseInt(this.$container.css("padding-right"),10);this.containerBottomPadding=parseInt(this.$container.css("padding-bottom"),10);this.containerLeftPadding=parseInt(this.$container.css("padding-left"),10);this.$overlay.hide().on("click",
function(){a.end();return!1});this.$lightbox.hide().on("click",function(d){"lightbox"===b(d.target).attr("id")&&a.end();return!1});this.$outerContainer.on("click",function(d){"lightbox"===b(d.target).attr("id")&&a.end();return!1});this.$lightbox.find(".lb-prev").on("click",function(){0===a.currentImageIndex?a.changeImage(a.album.length-1):a.changeImage(a.currentImageIndex-1);return!1});this.$lightbox.find(".lb-next").on("click",function(){a.currentImageIndex===a.album.length-1?a.changeImage(0):a.changeImage(a.currentImageIndex+
1);return!1});this.$lightbox.find(".lb-loader, .lb-close").on("click",function(){a.end();return!1})};c.prototype.start=function(a){function d(a){c.album.push({link:a.attr("href"),title:a.attr("data-title")||a.attr("title")})}var c=this,f=b(window);f.on("resize",b.proxy(this.sizeOverlay,this));b("select, object, embed").css({visibility:"hidden"});this.sizeOverlay();this.album=[];var g=0,e=a.attr("data-lightbox");if(e){e=b(a.prop("tagName")+'[data-lightbox="'+e+'"]');for(var h=0;h<e.length;h=++h)d(b(e[h])),
e[h]===a[0]&&(g=h)}else if("lightbox"===a.attr("rel"))d(a);else for(e=b(a.prop("tagName")+'[rel="'+a.attr("rel")+'"]'),h=0;h<e.length;h=++h)d(b(e[h])),e[h]===a[0]&&(g=h);a=f.scrollTop()+this.options.positionFromTop;f=f.scrollLeft();this.$lightbox.css({top:a+"px",left:f+"px"}).fadeIn(this.options.fadeDuration);this.options.disableScrolling&&b("body").addClass("lb-disable-scrolling");this.changeImage(g)};c.prototype.changeImage=function(a){var d=this;this.disableKeyboardNav();var c=this.$lightbox.find(".lb-image");
this.$overlay.fadeIn(this.options.fadeDuration);b(".lb-loader").fadeIn("slow");this.$lightbox.find(".lb-image, .lb-nav, .lb-prev, .lb-next, .lb-dataContainer, .lb-numbers, .lb-caption").hide();this.$outerContainer.addClass("animating");var f=new Image;f.onload=function(){c.attr("src",d.album[a].link);b(f);c.width(f.width);c.height(f.height);if(d.options.fitImagesInViewport){var g=b(window).width();var e=b(window).height();g=g-d.containerLeftPadding-d.containerRightPadding-20;e=e-d.containerTopPadding-
d.containerBottomPadding-120;d.options.maxWidth&&d.options.maxWidth<g&&(g=d.options.maxWidth);d.options.maxHeight&&d.options.maxHeight<g&&(e=d.options.maxHeight);if(f.width>g||f.height>e)f.width/g>f.height/e?(e=g,g=parseInt(f.height/(f.width/e),10)):(g=e,e=parseInt(f.width/(f.height/g),10)),c.width(e),c.height(g)}d.sizeContainer(c.width(),c.height())};f.src=this.album[a].link;this.currentImageIndex=a};c.prototype.sizeOverlay=function(){this.$overlay.width(b(document).width()).height(b(document).height())};
c.prototype.sizeContainer=function(a,b){function c(){d.$lightbox.find(".lb-dataContainer").width(h);d.$lightbox.find(".lb-prevLink").height(k);d.$lightbox.find(".lb-nextLink").height(k);d.showImage()}var d=this,g=this.$outerContainer.outerWidth(),e=this.$outerContainer.outerHeight(),h=a+this.containerLeftPadding+this.containerRightPadding,k=b+this.containerTopPadding+this.containerBottomPadding;g!==h||e!==k?this.$outerContainer.animate({width:h,height:k},this.options.resizeDuration,"swing",function(){c()}):
c()};c.prototype.showImage=function(){this.$lightbox.find(".lb-loader").stop(!0).hide();this.$lightbox.find(".lb-image").fadeIn("slow");this.updateNav();this.updateDetails();this.preloadNeighboringImages();this.enableKeyboardNav()};c.prototype.updateNav=function(){var a=!1;try{document.createEvent("TouchEvent"),a=this.options.alwaysShowNavOnTouchDevices?!0:!1}catch(d){}this.$lightbox.find(".lb-nav").show();1<this.album.length&&(this.options.wrapAround?(a&&this.$lightbox.find(".lb-prev, .lb-next").css("opacity",
"1"),this.$lightbox.find(".lb-prev, .lb-next").show()):(0<this.currentImageIndex&&(this.$lightbox.find(".lb-prev").show(),a&&this.$lightbox.find(".lb-prev").css("opacity","1")),this.currentImageIndex<this.album.length-1&&(this.$lightbox.find(".lb-next").show(),a&&this.$lightbox.find(".lb-next").css("opacity","1"))))};c.prototype.updateDetails=function(){var a=this;if("undefined"!==typeof this.album[this.currentImageIndex].title&&""!==this.album[this.currentImageIndex].title)this.$lightbox.find(".lb-caption").html(this.album[this.currentImageIndex].title).fadeIn("fast").find("a").on("click",
function(a){void 0!==b(this).attr("target")?window.open(b(this).attr("href"),b(this).attr("target")):location.href=b(this).attr("href")});if(1<this.album.length&&this.options.showImageNumberLabel){var c=this.imageCountLabel(this.currentImageIndex+1,this.album.length);this.$lightbox.find(".lb-number").text(c).fadeIn("fast")}else this.$lightbox.find(".lb-number").hide();this.$outerContainer.removeClass("animating");this.$lightbox.find(".lb-dataContainer").fadeIn(this.options.resizeDuration,function(){return a.sizeOverlay()})};
c.prototype.preloadNeighboringImages=function(){this.album.length>this.currentImageIndex+1&&((new Image).src=this.album[this.currentImageIndex+1].link);0<this.currentImageIndex&&((new Image).src=this.album[this.currentImageIndex-1].link)};c.prototype.enableKeyboardNav=function(){b(document).on("keyup.keyboard",b.proxy(this.keyboardAction,this))};c.prototype.disableKeyboardNav=function(){b(document).off(".keyboard")};c.prototype.keyboardAction=function(a){a=a.keyCode;var b=String.fromCharCode(a).toLowerCase();
if(27===a||b.match(/x|o|c/))this.end();else if("p"===b||37===a)0!==this.currentImageIndex?this.changeImage(this.currentImageIndex-1):this.options.wrapAround&&1<this.album.length&&this.changeImage(this.album.length-1);else if("n"===b||39===a)this.currentImageIndex!==this.album.length-1?this.changeImage(this.currentImageIndex+1):this.options.wrapAround&&1<this.album.length&&this.changeImage(0)};c.prototype.end=function(){this.disableKeyboardNav();b(window).off("resize",this.sizeOverlay);this.$lightbox.fadeOut(this.options.fadeDuration);
this.$overlay.fadeOut(this.options.fadeDuration);b("select, object, embed").css({visibility:"visible"});this.options.disableScrolling&&b("body").removeClass("lb-disable-scrolling")};return new c});